# -*- coding: utf-8 -*-
"""
10_generate_figures.py  —  SINGLE ENTRY POINT for all final manuscript figures.
================================================================================
RULE (enforced, per FINAL_ANALYSIS_PROTOCOL §4):
  Every figure generated by the project must have a 1-line PROVENANCE comment:
    # Figure X <Short title>  <--  input.csv --(10_generate_figures.py)--> FigureX_xxx.pdf
  No figure in 05_FINAL_FIGURES/ is ever hand-copied from a historical folder.

Output: PDF (vector) + 600 dpi PNG into 05_FINAL_FIGURES/main/ and supplementary/.
NO "Fig X" text inside any image canvas (config policy).

Figures generated:
  Figure 2  Technical Roadmap      <-- FINAL_ANALYSIS_PROTOCOL §2 --(10_generate_figures.py)--> Figure2_Roadmap.pdf
  Figure 3  4-Quadrant Scatter     <-- topic_info.csv --(10_generate_figures.py)--> Figure3_QuadrantScatter.pdf
  Figure 4  Project-Level RTAS    <-- project_level_summary.csv --(10_generate_figures.py)--> Figure4_ProjectLevel.pdf
  Figure 5  Top-20 Colleges Bar  <-- college_rtas_top20.csv (college_fontsize=10) --(10_generate_figures.py)--> Figure5_Top20Colleges.pdf
  Figure 6  HLM Forest Plot       <-- hlm_coefficients.csv (SAME source as Table 6) --(10_generate_figures.py)--> Figure6_HLM_Forest.pdf
  Figure 7  Transition Matrix     <-- transition_probabilities_year_tercile.csv --(10_generate_figures.py)--> Figure7_TransitionMatrix.pdf
  Figure 8  Diffusion Lag Hist   <-- diffusion_lag_histogram_bins.csv --(10_generate_figures.py)--> Figure8_DiffusionLag.pdf
  Figure 9  Diffusion by Quadrant<-- diffusion_lag_aggregate_stats.csv --(10_generate_figures.py)--> Figure9_DiffusionByQuadrant.pdf
  Figure 10 Matthew Lorenz+Pareto<-- supervisor_gini_pareto.csv --(10_generate_figures.py)--> Figure10_MatthewEffect.pdf
  Figure 11 Quadrant Summary Bars<-- quadrant_overall_summary.csv --(10_generate_figures.py)--> Figure11_QuadrantSummary.pdf
  Figure 12 College RTAS Ranking  <-- college_rtas_top20.csv (college_fontsize=10) --(10_generate_figures.py)--> Figure12_CollegeRTAS.pdf
  Figure 13 Topic Yearly Stacked  <-- topic_yearly_prevalence_for_diffusion_lag.csv (boundary_fontsize=6) --(10_generate_figures.py)--> Figure13_TopicStackedArea.pdf
"""
from __future__ import annotations
import os, sys, json, re, warnings; warnings.filterwarnings('ignore')
from pathlib import Path

import yaml
import numpy as np
import pandas as pd
from scipy import stats as _stats  # Welch t / Mann-Whitney for boxplot pairwise stars
import matplotlib
matplotlib.use('Agg')  # non-interactive backend
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.gridspec as gridspec

# ================================================================
# 0. Global style configuration
# ================================================================
ROOT = Path(__file__).resolve().parents[1]
CFG = yaml.safe_load((ROOT / '00_README' / 'final_config.yaml').read_text(encoding='utf-8'))
VCFG = CFG.get('visualization', {})
DPI = int(VCFG.get('png_dpi', 600))
OUT_MAIN = ROOT / VCFG.get('output_main', '05_FINAL_FIGURES/main/')
OUT_SUPP = ROOT / VCFG.get('output_supp', '05_FINAL_FIGURES/supplementary/')
OUT_MAIN.mkdir(parents=True, exist_ok=True)
OUT_SUPP.mkdir(parents=True, exist_ok=True)

# CJK font setup for Chinese college names
for font in ['Microsoft YaHei', 'SimHei', 'Noto Sans CJK SC', 'Arial Unicode MS']:
    try:
        matplotlib.font_manager.findfont(font, fallback_to_default=False)
        CJK_FONT = font
        break
    except Exception:
        continue
else:
    CJK_FONT = 'SimHei'

plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': [CJK_FONT, 'DejaVu Sans', 'Arial'],
    'axes.unicode_minus': False,
    'figure.dpi': 100,
    'savefig.dpi': DPI,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.15,
    'font.size': 9,
    'axes.titlesize': 11,
    'axes.labelsize': 10,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'legend.fontsize': 8,
    'axes.spines.top': False,
    'axes.spines.right': False,
    'axes.grid': True,
    'grid.alpha': 0.3,
    'grid.linestyle': '--',
})

# Color palette (serious, publication-quality)
COLORS = {
    'blue':   '#2E5C8A',
    'red':    '#C0392B',
    'green':  '#27AE60',
    'orange': '#E67E22',
    'purple': '#7D3C98',
    'gray':   '#7F8C8D',
    'teal':   '#1ABC9C',
    'navy':   '#1A237E',
}
QUADRANT_COLORS = {
    'HRHT_HighResearch_HighTraining': '#C0392B',  # red — both high
    'HRLT_HighResearch_LowTraining':  '#E67E22',  # orange — research leads
    'LRHT_LowResearch_HighTraining':  '#27AE60',  # green — training leads
    'LRLT_LowResearch_LowTraining':   '#7F8C8D',  # gray — both low
}
QUADRANT_SHORT = {
    'HRHT_HighResearch_HighTraining': 'HRHT',
    'HRLT_HighResearch_LowTraining':  'HRLT',
    'LRHT_LowResearch_HighTraining': 'LRHT',
    'LRLT_LowResearch_LowTraining':   'LRLT',
}

# Chinese college name → English translation (for ALL-English figure policy)
COLLEGE_EN = {
    '中国南极测绘研究中心': 'Chinese Antarctic Center for Surveying & Mapping',
    '化学与分子科学学院': 'College of Chemistry & Molecular Sciences',
    '工业科学研究院': 'Institute of Industrial Science',
    '测绘遥感信息工程国家重点实验室': 'State Key Lab of Info. Eng. in Surveying & Remote Sensing',
    '国家网络安全学院': 'School of Cyber Science',
    '遥感信息工程学院': 'School of Remote Sensing & Info. Engineering',
    '计算机学院': 'School of Computer Science',
    '水利水电学院': 'College of Water Resources & Hydropower',
    '物理科学与技术学院': 'School of Physics & Technology',
    '电子信息学院': 'School of Electronic Information',
    '电气与自动化学院': 'School of Electrical Engineering & Automation',
    '资源与环境科学学院': 'School of Resource & Environmental Sciences',
    '城市设计学院': 'School of Urban Design',
    '土木建筑工程学院': 'School of Civil & Architectural Engineering',
    '动力与机械学院': 'School of Power & Mechanical Engineering',
    '数学与统计学院': 'School of Mathematics & Statistics',
    '生命科学学院': 'College of Life Sciences',
    '经济与管理学院': 'School of Economics & Management',
    '信息管理学院': 'School of Information Management',
    '新闻与传播学院': 'School of Journalism & Communication',
    '政治与公共管理学院': 'School of Political Science & Public Management',
    '法学院': 'Law School',
    '文学院': 'School of Chinese Language & Literature',
    '哲学学院': 'School of Philosophy',
    '历史学院': 'School of History',
    '外国语言文学学院': 'School of Foreign Languages & Literature',
    '艺术与设计学院': 'School of Arts & Design',
    '艺术学院': 'School of Arts',
    '第一临床学院': 'First Clinical College',
    '第二临床学院': 'Second Clinical College',
    '基础医学院': 'School of Basic Medical Sciences',
    '口腔医学院': 'School of Stomatology',
    '公共卫生学院': 'School of Public Health',
    '药学院': 'School of Pharmaceutical Sciences',
    '护理学院': 'School of Nursing',
    '健康学院': 'School of Health',
    '印刷与包装系': 'Dept. of Printing & Packaging',
    '弘毅学堂': 'Hongyi College',
    '马克思主义学院': 'School of Marxism',
    '测绘学院': 'School of Geodesy & Geomatics',
    '国际教育学院': 'School of International Education',
}
def translate_college(name):
    """Translate Chinese college name to English; return original if not found."""
    return COLLEGE_EN.get(str(name).strip(), str(name).strip())

# Data root
DATA = ROOT / '03_FINAL_ANALYSIS'

def savefig(fig, name, subdir='main'):
    """Save figure as PDF + PNG with provenance."""
    out_dir = OUT_MAIN if subdir == 'main' else OUT_SUPP
    pdf_path = out_dir / f'{name}.pdf'
    png_path = out_dir / f'{name}.png'
    fig.savefig(pdf_path, format='pdf', dpi=DPI)
    fig.savefig(png_path, format='png', dpi=DPI)
    plt.close(fig)
    print(f'  ✓ {name}.pdf + {name}.png  →  {out_dir}')

def provenance(fig_num, title, input_csv, script='10_generate_figures.py'):
    """Print provenance line."""
    print(f'# Figure {fig_num} {title}  <--  {input_csv} --({script})--> see output files')

# ================================================================
# Figure 2: Technical Roadmap (schematic)
# ================================================================
def fig2_roadmap():
    provenance(2, 'Technical Roadmap', 'FINAL_ANALYSIS_PROTOCOL.md §2')
    fig, ax = plt.subplots(figsize=(11.5, 6.2))
    ax.set_xlim(0, 11.5); ax.set_ylim(0, 6.4); ax.axis('off')

    # 3-tier layout: each tier strictly horizontal, tiers separated by wide gaps.
    # Arrows are ONLY same-tier horizontal or cross-tier near-vertical,
    # so no arrow can ever cross a box.
    BW, BH = 2.3, 1.15          # box width/height
    R1, R2, R3 = 4.7, 2.45, 0.25  # tier baseline y
    boxes = [
        # Tier 1 (pipeline): 4 boxes, evenly spaced
        (0.40, R1, BW, BH, 'Data Collection\n3,714 projects (CN)\n56,901 papers (EN)\nOpenAlex 2020-2024', COLORS['blue']),
        (3.30, R1, BW, BH, 'Embedding\nMultilingual MiniLM\nL12-v2 (384-dim)\nL2-normalized', COLORS['teal']),
        (6.20, R1, BW, BH, 'RTAS Computation\nCosine similarity\nMean aggregation\nCumulative [2020, t]', COLORS['green']),
        (9.10, R1, BW, BH, 'RTAS Frozen\n5 variants tested\nPrimary = mean\nSpearman = 0.405', COLORS['navy']),
        # Tier 2 (analyses): 5 boxes
        (0.40, R2, 1.95, BH, 'Heterogeneity (RQ1)\nF(2,3711)=35.7\nη²=1.89%\nd=0.352', COLORS['blue']),
        (2.60, R2, 1.95, BH, 'BERTopic (RQ2)\nUMAP+HDBSCAN\nK=886 topics\n4-quadrant', COLORS['orange']),
        (4.80, R2, 1.95, BH, 'HLM (RQ3)\nMixedLM RE\nICC=0.738\n39 colleges', COLORS['purple']),
        (7.00, R2, 1.95, BH, 'Matthew (RQ4)\nGini=0.767\nTop5%=34.0%\nlag-OR=2.25***', COLORS['red']),
        (9.20, R2, 1.95, BH, 'RI-CLPM (future)\npanel built\nnot estimated\n(see MS sec.7)', COLORS['teal']),
        # Tier 3 (downstream): 1 box, aligned under BERTopic
        (2.60, R3, 1.95, BH, 'Diffusion Lag (RQ2)\n29/886 defined\nHRLT median +0.5 yr', COLORS['gray']),
    ]
    edges = {}
    for x, y, w, h, text, color in boxes:
        rect = mpatches.FancyBboxPatch((x, y), w, h, boxstyle='round,pad=0.07',
                                        facecolor=color, alpha=0.13, edgecolor=color, linewidth=1.4)
        ax.add_patch(rect)
        ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=6.3, fontweight='bold',
                color=color, linespacing=1.35)
        edges[(x, y, w, h)] = {
            'top': (x + w/2, y + h), 'bottom': (x + w/2, y),
            'left': (x, y + h/2), 'right': (x + w, y + h/2),
        }

    def arrow(bf, bt, sf='right', st='left'):
        p1 = edges[bf][sf]; p2 = edges[bt][st]
        ax.annotate('', xy=p2, xytext=p1,
                    arrowprops=dict(arrowstyle='->', color='#555555', lw=1.2,
                                    connectionstyle='arc3,rad=0'),
                    zorder=1)

    b = [bb[:4] for bb in boxes]
    # Tier 1 horizontal flow
    arrow(b[0], b[1], 'right', 'left')
    arrow(b[1], b[2], 'right', 'left')
    arrow(b[2], b[3], 'right', 'left')
    # Tier 1 → Tier 2: straight vertical drops between aligned columns (wide gap, no boxes in between)
    arrow(b[0], b[4], 'bottom', 'top')       # data → heterogeneity
    arrow(b[1], b[5], 'bottom', 'top')       # embedding → BERTopic
    arrow(b[2], b[6], 'bottom', 'top')       # RTAS → HLM
    arrow(b[3], b[7], 'bottom', 'top')       # frozen → Matthew
    arrow(b[3], b[8], 'bottom', 'top')       # frozen → RI-CLPM (near-vertical)
    # Tier 2 → Tier 3: BERTopic straight down to Diffusion Lag
    arrow(b[5], b[9], 'bottom', 'top')

    ax.set_title('RTAS Technical Roadmap — Data to Discovery',
                 fontsize=12, fontweight='bold', pad=10)
    fig.tight_layout()
    savefig(fig, 'Figure2_Roadmap')

# ================================================================
# Figure 3: 4-Quadrant Scatter (individual topics)
# ================================================================
def fig3_quadrant_scatter():
    inp = 'topic_model/topic_info.csv'
    provenance(3, '4-Quadrant Scatter', inp)
    ti = pd.read_csv(DATA / 'topic_model' / 'topic_info.csv')
    ti = ti[ti['Topic'] >= 0].copy()  # exclude outlier row
    fig, ax = plt.subplots(figsize=(7, 6))
    for q, color in QUADRANT_COLORS.items():
        sub = ti[ti['quadrant'] == q]
        if len(sub) == 0: continue
        ax.scatter(sub['frac_paper'] * 100, sub['frac_project'] * 100,
                   s=sub['Count'] * 0.3, c=color, alpha=0.6, edgecolors='white', linewidth=0.3,
                   label=f'{QUADRANT_SHORT[q]} (n={len(sub)})', zorder=3)
    # Threshold lines
    thr_p = ti['thr_paper_pct_used'].iloc[0] if 'thr_paper_pct_used' in ti.columns else 0.31
    thr_r = ti['thr_project_pct_used'].iloc[0] if 'thr_project_pct_used' in ti.columns else 0.5
    ax.axhline(y=thr_r, color='#999999', linestyle='--', linewidth=0.8, alpha=0.5)
    ax.axvline(x=thr_p, color='#999999', linestyle='--', linewidth=0.8, alpha=0.5)
    # Force BOTH axes to start exactly at 0 so the single origin (0,0) is the
    # bottom-left corner where the x-0 and y-0 ticks coincide (no floating 0 ticks).
    xmax = float((ti['frac_paper'] * 100).max())
    ymax = float((ti['frac_project'] * 100).max())
    ax.set_xlim(0, xmax * 1.06)
    ax.set_ylim(0, ymax * 1.12)
    ax.set_xlabel('Paper Prevalence (%)', fontweight='bold')
    ax.set_ylabel('Project Prevalence (%)', fontweight='bold')
    ax.set_title('Topic Distribution across Research-Training Quadrants', fontweight='bold')
    ax.legend(loc='upper right', framealpha=0.9, fontsize=7)
    # Quadrant labels — anchored INSIDE the true quadrant regions relative to the
    # threshold lines: vertical line = paper threshold, horizontal = project threshold.
    #   top-right = HRHT (high paper, high project)
    #   top-left  = LRHT (low paper, high project)
    #   bot-right = HRLT (high paper, low project)
    #   bot-left  = LRLT (low paper, low project)
    ytop = ax.get_ylim()[1]; xright = ax.get_xlim()[1]
    import matplotlib.patheffects as _pe3
    _halo3 = [_pe3.withStroke(linewidth=2.2, foreground='white')]
    def _qlabel(x, y, txt, color, alpha):
        ax.text(x, y, txt, ha='left', fontsize=9, color=color, alpha=alpha,
                fontweight='bold', path_effects=_halo3, zorder=5)
    _qlabel(xright * 0.75, ytop * 0.92, 'HRHT', QUADRANT_COLORS['HRHT_HighResearch_HighTraining'], 0.55)
    _qlabel(0.015, ytop * 0.88, 'LRHT', QUADRANT_COLORS['LRHT_LowResearch_HighTraining'], 0.75)
    _qlabel(xright * 0.58, thr_r * 0.35, 'HRLT', QUADRANT_COLORS['HRLT_HighResearch_LowTraining'], 0.6)
    _qlabel(0.012, thr_r * 0.62, 'LRLT', QUADRANT_COLORS['LRLT_LowResearch_LowTraining'], 0.9)
    fig.tight_layout()
    savefig(fig, 'Figure3_QuadrantScatter')

# ================================================================
# Figure 4: Project-Level RTAS Comparison (校/省/国)
#   Left panel: mean ± 95% CI bars; Right panel: full distribution boxplot
#   (raw per-project RTAS from table5_full — nothing hidden, nothing crowded)
# ================================================================
def fig4_project_level():
    """Figure 4 split into TWO clean standalone figures (v0.9.1 round-6 user request):
      Figure4a_MeanCI       — mean RTAS bars with 95% CI only, no in-plot clutter.
      Figure4b_Distribution — boxplot + 3,714 jitter points only; ALL numeric tables
                              (8-number summaries + Welch/Tukey pairwise stats) moved
                              to a dedicated info panel BELOW the axes (figure coords).
    """
    fig4a_mean_ci()
    fig4b_distribution()

def _fig4_load():
    """Shared loader for Fig 4a/4b: tier summary + raw per-project RTAS + Tukey CSV."""
    d = pd.read_csv(DATA / 'heterogeneity' / 'project_level_summary.csv')
    level_en = {'校级': 'University', '省级': 'Provincial', '国家级': 'National'}
    d['_level_en'] = d['_level_label'].map(level_en).fillna(d['_level_label'])
    d = d.sort_values('mean')
    raw = pd.read_csv(ROOT / '01_DATA' / 'final_analysis' / 'table5_project_dataset_n3714_full.csv')
    raw['level_en'] = raw['_level_label'] if '_level_label' in raw.columns else raw['项目等级']
    raw['level_en'] = raw['level_en'].map(level_en).fillna(raw['level_en'])
    order = d['_level_en'].tolist()  # University < Provincial < National by mean
    d['sem'] = d['sd'] / np.sqrt(d['n'])
    d['ci95'] = 1.96 * d['sem']
    data_box = [raw.loc[raw['level_en'] == lv, 'rtas'].dropna().values for lv in order]
    return d, raw, order, data_box

def _fig4_pairwise(data_box):
    """Compute Welch + Cohen d per pair and read strict Tukey HSD from frozen CSV."""
    tukey = pd.read_csv(DATA / 'heterogeneity' / 'tukey_project_level_pairwise.csv')
    cn_to_idx = dict(zip(['校级', '省级', '国家级'], range(3)))
    tukey_dict = {}
    for _, r in tukey.iterrows():
        ia, ib = sorted([cn_to_idx[r['group1']], cn_to_idx[r['group2']]])
        tukey_dict[(ia, ib)] = {'p_adj': float(r['p-adj']), 'meandiff': float(r['meandiff']),
                                'reject': bool(r['reject']),
                                'lower': float(r['lower']), 'upper': float(r['upper'])}
    out = []
    for (ia, ib) in [(0, 1), (1, 2), (0, 2)]:
        va, vb = data_box[ia], data_box[ib]
        _, pw = _stats.ttest_ind(va, vb, equal_var=False, alternative='two-sided')
        d_ = (np.mean(vb) - np.mean(va)) / np.sqrt((np.var(va, ddof=1) + np.var(vb, ddof=1)) / 2)
        out.append((ia, ib, pw, d_, tukey_dict[(ia, ib)]))
    return out

def fig4a_mean_ci():
    inp = 'heterogeneity/project_level_summary.csv'
    provenance(4, 'Fig 4a Project-Level Mean RTAS with 95% CI', inp)
    d, _, order, _ = _fig4_load()
    colors = [COLORS['blue'], COLORS['orange'], COLORS['red']]
    x = np.arange(len(d))
    fig, ax = plt.subplots(figsize=(7.6, 6.0))
    bars = ax.bar(x, d['mean'], yerr=d['ci95'], capsize=7,
                  color=colors, alpha=0.88, edgecolor='white', linewidth=0.6, width=0.56,
                  error_kw=dict(ecolor='#222', elinewidth=1.3, capthick=1.3))
    for xi, (bar, val, n, ci) in enumerate(zip(bars, d['mean'], d['n'], d['ci95'])):
        ax.text(xi, val + ci + 0.004, f'{val:.3f}', ha='center', va='bottom',
                fontsize=12, fontweight='bold', color='#111')
        ax.text(xi, val / 2, f'n = {n:,}', ha='center', va='center', fontsize=9.5,
                color='white', fontweight='bold')
    ax.set_xticks(x); ax.set_xticklabels(order, fontsize=11.5)
    ax.set_ylabel('RTAS (mean ± 95% CI)', fontweight='bold', fontsize=11)
    ax.set_xlabel('Project Level', fontweight='bold', fontsize=11)
    ax.set_ylim(0, max(d['mean'] + d['ci95']) * 1.22)
    ax.set_title('(a) Mean Research-Training Alignment Score by Project Level\n'
                 'One-way ANOVA: F(2, 3711) = 35.72,  p = 4.3e-16,  η² = 1.89%',
                 fontweight='bold', fontsize=11)
    fig.tight_layout()
    savefig(fig, 'Figure4a_MeanCI')

def fig4b_distribution():
    inp = 'heterogeneity/project_level_summary.csv + tukey_project_level_pairwise.csv + table5_project_dataset_n3714_full.csv'
    provenance(4, 'Fig 4b Project-Level RTAS Distribution (box+jitter, stats panel below)', inp)
    d, raw, order, data_box = _fig4_load()
    colors = [COLORS['blue'], COLORS['orange'], COLORS['red']]
    x = np.arange(len(order))

    fig = plt.figure(figsize=(10.5, 9.6))
    ax = fig.add_axes([0.08, 0.42, 0.90, 0.48])  # leave large bottom info-panel zone

    bp = ax.boxplot(data_box, positions=x, widths=0.38, patch_artist=True, showmeans=True,
                    meanprops=dict(marker='D', markerfacecolor='white', markeredgecolor='#222', markersize=8),
                    medianprops=dict(color='#111', linewidth=1.8),
                    whiskerprops=dict(linewidth=1.2),
                    capprops=dict(linewidth=1.2),
                    flierprops=dict(marker='o', markersize=3, markeredgecolor='none',
                                    markerfacecolor='#aaa', alpha=0.5))
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color); patch.set_alpha(0.25); patch.set_edgecolor(color); patch.set_linewidth(1.4)
    rng = np.random.default_rng(42)
    for xi, vals, color in zip(x, data_box, colors):
        jitter = rng.normal(0, 0.045, len(vals))
        ax.scatter(xi + jitter, vals, s=5, c=color, alpha=0.22, edgecolors='none', zorder=2)
    ax.axhline(0, color='#999', linewidth=0.7, linestyle=':')

    # Brackets: ONLY the strict Tukey verdict stars (full numbers in bottom panel)
    pairs = _fig4_pairwise(data_box)
    allmax = max(float(np.max(v)) for v in data_box)
    allmin = min(float(np.min(v)) for v in data_box)
    yrange = allmax - allmin
    bracket_h = yrange * 0.06
    y0 = allmax + yrange * 0.16
    spec = [((0, 1), 0.0, COLORS['navy']), ((1, 2), 1.7, '#aa5500'), ((0, 2), 3.6, COLORS['red'])]
    for (ia, ib), hrel, col in spec:
        tk = [p for p in pairs if p[0] == ia and p[1] == ib][0][-1]
        verdict = '***' if tk['reject'] else 'ns'
        yb = y0 + hrel * bracket_h
        riser = bracket_h * 0.22
        ax.plot([x[ia], x[ia]], [yb - riser, yb], color=col, lw=1.4, clip_on=False)
        ax.plot([x[ib], x[ib]], [yb - riser, yb], color=col, lw=1.4, clip_on=False)
        ax.plot([x[ia], x[ib]], [yb, yb], color=col, lw=1.4, clip_on=False)
        ax.text((x[ia] + x[ib]) / 2, yb + bracket_h * 0.05, verdict,
                ha='center', va='bottom', fontsize=11, fontweight='bold', color=col)
    ax.set_ylim(allmin - yrange * 0.06, y0 + 5.3 * bracket_h)
    ax.set_xticks(x); ax.set_xticklabels(order, fontsize=11.5)
    ax.set_ylabel('RTAS (per project, 3,714 observations)', fontweight='bold', fontsize=10.5)
    ax.set_xlabel('Project Level', fontweight='bold', fontsize=10.5)
    fig.suptitle('(b) RTAS per-project distribution  —  box = Q1–Q3,  bold line = median,  diamond = mean,  whiskers = 1.5·IQR,  dots = 3,714 individual projects\n'
                 'Brackets = post-hoc pairwise verdict (*** / ns); full statistics and 8-number summaries in the panel below.',
                 fontweight='bold', fontsize=10.5, y=0.965)

    # ---- Bottom info panel (figure-fraction coordinates, stable under tight_layout) ----
    # 1) Three per-tier 8-number summary columns
    col_x = [0.20, 0.50, 0.80]
    for xi, vals, lv, color, cx in zip(x, data_box, order, colors, col_x):
        n = len(vals); mean_v = float(np.mean(vals)); med_v = float(np.median(vals))
        q1 = float(np.percentile(vals, 25)); q3 = float(np.percentile(vals, 75))
        sd = float(np.std(vals, ddof=1))
        lo_w = float(bp['whiskers'][2*xi].get_ydata()[0])
        hi_w = float(bp['whiskers'][2*xi+1].get_ydata()[0])
        block = (f"{lv}  (n = {n:,})\n"
                 f"─────────────────────\n"
                 f" mean  = {mean_v:.4f}\n"
                 f" ± SD  = {sd:.4f}\n"
                 f" med   = {med_v:.4f}\n"
                 f" Q1/Q3 = {q1:.4f} / {q3:.4f}\n"
                 f" IQR   = {q3-q1:.4f}\n"
                 f" whisk = [{lo_w:.3f}, {hi_w:.3f}]\n"
                 f" range = [{float(np.min(vals)):.3f}, {float(np.max(vals)):.3f}]")
        fig.text(cx, 0.36, block, ha='center', va='top', fontsize=8.2, family='Consolas',
                 color='#111', linespacing=1.35,
                 bbox=dict(boxstyle='round,pad=0.45', facecolor=color, alpha=0.07,
                           edgecolor=color, linewidth=1.0))

    # 2) Pairwise comparison table (Welch vs strict Tukey side by side)
    def _ps(p):
        return '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
    lines = ['Pairwise tests (Welch = uncorrected two-sample t;  Tukey HSD = strict family-wise corrected)',
             'pair            Welch p (Cohen d)              Tukey HSD p-adj     Tukey 95% Δ-CI              verdict',
             '────────────────────────────────────────────────────────────────────────────────────────────────────']
    pair_names = {(0, 1): 'U vs P', (1, 2): 'P vs N', (0, 2): 'U vs N'}
    for (ia, ib, pw, dco, tk) in pairs:
        verdict = 'PASS ***' if tk['reject'] else 'FAIL (ns, CI crosses 0)'
        lines.append(f"{pair_names[(ia,ib)]:<9}  {pw:8.2e}  {_ps(pw):<3} (d={dco:+.3f})      "
                     f"{tk['p_adj']:8.4f}  {_ps(tk['p_adj']):<3}      [{tk['lower']:+.4f}, {tk['upper']:+.4f}]     {verdict}")
    lines.append('')
    lines.append('Strict multiplicity-corrected ordering:  University < Provincial ≤ National.  '
                 'P vs N is borderline * in Welch but FAILS Tukey HSD (p-adj = 0.082, Δ-CI crosses 0).')
    fig.text(0.5, 0.165, '\n'.join(lines), ha='center', va='top', fontsize=7.8, family='Consolas',
             color='#222', linespacing=1.45,
             bbox=dict(boxstyle='round,pad=0.55', facecolor='#f1f1f1', alpha=0.9,
                       edgecolor='#888', linewidth=0.9))
    savefig(fig, 'Figure4b_Distribution')

# ================================================================
# Figure 5: Top-20 Colleges Bar Chart (horizontal, college_fontsize=10)
# ================================================================
def fig5_top20_colleges():
    inp = 'heterogeneity/college_rtas_top20.csv'
    provenance(5, 'Top-20 Colleges by RTAS', inp)
    d = pd.read_csv(DATA / 'heterogeneity' / 'college_rtas_top20.csv')
    d = d.sort_values('rtas_mean')  # ascending for horizontal bar
    d['college_en'] = d['college'].apply(translate_college)
    fig, ax = plt.subplots(figsize=(9, 8))
    # Color mapped to VALUE (not rank) so red/green meaning is exact
    norm = plt.Normalize(vmin=d['rtas_mean'].min(), vmax=d['rtas_mean'].max())
    cmap = plt.cm.RdYlGn  # red = low RTAS, green = high RTAS
    colors = cmap(norm(d['rtas_mean'].values))
    bars = ax.barh(range(len(d)), d['rtas_mean'], color=colors, edgecolor='white', linewidth=0.3, height=0.7)
    ax.set_yticks(range(len(d)))
    ax.set_yticklabels(d['college_en'].values, fontsize=9)  # English names, fontsize=10 per config
    ax.set_xlabel('RTAS (mean)', fontweight='bold')
    ax.set_title('Top-20 Colleges by Research-Training Alignment Score',
                 fontweight='bold', fontsize=11)
    for i, (val, n) in enumerate(zip(d['rtas_mean'], d['n_projects'])):
        ax.text(val + 0.003, i, f'{val:.3f} (n={n})', va='center', fontsize=7)
    ax.set_xlim(0, max(d['rtas_mean']) * 1.25)
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    cbar = fig.colorbar(sm, ax=ax, shrink=0.55, pad=0.12)
    cbar.set_label('RTAS color scale:  red = lower alignment  →  green = higher alignment', fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    fig.tight_layout()
    savefig(fig, 'Figure5_Top20Colleges')

# ================================================================
# Figure 6: HLM Forest Plot (SINGLE SOURCE = hlm_coefficients.csv = Table 6)
# ================================================================
def fig6_hlm_forest():
    inp = 'hlm/hlm_mixedlm_v2b_primary_coefficients.csv'
    provenance(6, 'HLM v2.0b Random-Intercept MixedLM Forest Plot', inp)
    d = pd.read_csv(DATA / 'hlm' / 'hlm_mixedlm_v2b_primary_coefficients.csv')
    # Exclude intercept and Group Var (variance component, not a predictor)
    d_plot = d[~d['term'].isin(['Intercept', 'Group Var', 'const'])].copy()
    # Friendly labels
    label_map = {
        'is_provincial': 'Provincial (vs. University)',
        'is_national': 'National (vs. University)',
        'year_centered': 'Year (per year, centered at 2022)',
        'log_prior3y': 'Advisor pre-project 3y works  log(1+x)',
        'log_prior_supervision': 'Advisor prior supervised projects  log(1+x)',
        'log_supervision': 'Advisor prior supervised projects  log(1+x)',
        'advisor_count': 'Advisor count',
        'advisor_recent_3y_works_mean': 'Advisor recent-3y works (mean)',
        'advisor_cited_by_count_all_mean': 'Advisor cited-by count (mean)',
    }
    d_plot['label'] = d_plot['term'].map(label_map).fillna(d_plot['term'])
    d_plot = d_plot.sort_values('coef', ascending=True).reset_index(drop=True)

    # Parse ICC / nobs / ngroups from v2b summary (single source)
    icc_val, nobs_val, ngrp_val = 'NA', 'NA', 'NA'
    summ = (DATA / 'hlm' / 'hlm_mixedlm_v2b_primary_summary.txt').read_text(encoding='utf-8')
    m = re.search(r'ICC=([\d.]+)', summ)
    if m: icc_val = m.group(1)
    m = re.search(r'n=([\d,]+),\s*colleges=(\d+)', summ)
    if m:
        nobs_val, ngrp_val = m.group(1), m.group(2)

    fig = plt.figure(figsize=(9.8, 7.6))
    ax = fig.add_axes([0.30, 0.46, 0.66, 0.44])  # wide left margin for labels; bottom zone = table
    y_pos = np.arange(len(d_plot))
    x_range_min = min(d_plot['ci_low'].min(), 0)
    x_range_max = max(d_plot['ci_high'].max(), 0.001)
    x_span = x_range_max - x_range_min
    ax.set_xlim(x_range_min - 0.18 * x_span, x_range_max + 0.22 * x_span)

    def _sig_color(sig):
        return (COLORS['green'] if sig == '***'
                else COLORS['orange'] if sig == '*'
                else COLORS['red'] if sig == '**'
                else COLORS['gray'])

    for i, (_, row) in enumerate(d_plot.iterrows()):
        sig = row['stars']
        color = _sig_color(sig)
        ax.errorbar(row['coef'], i,
                    xerr=[[row['coef'] - row['ci_low']],
                          [row['ci_high'] - row['coef']]],
                    fmt='o', color=COLORS['navy'], ecolor=color, capsize=5,
                    markersize=9, linewidth=2.0, zorder=3)
        # Small significance star just right of the CI cap
        ax.text(row['ci_high'] + 0.03 * x_span, i, sig, ha='left', va='center',
                fontsize=11, fontweight='bold', color=color)
    ax.axvline(x=0, color='#333333', linestyle='--', linewidth=1.0, alpha=0.6)
    ax.axvspan(0, ax.get_xlim()[1], facecolor=COLORS['green'], alpha=0.05, zorder=0)
    ax.axvspan(ax.get_xlim()[0], 0, facecolor=COLORS['red'], alpha=0.05, zorder=0)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(d_plot['label'].values, fontsize=10)
    ax.set_xlabel('Coefficient (β) ± 95% CI   (green zone = positive alignment, red zone = negative)',
                  fontweight='bold', fontsize=9.5)
    fig.suptitle('Two-level mixed model (projects nested in colleges, random intercept)\n'
                 f'ICC = {icc_val}   |   n = {nobs_val} projects   |   {ngrp_val} college groups   |   '
                 'exact β, 95% CI, p-values in the table below',
                 fontweight='bold', fontsize=11, y=0.97)

    # ---- Numeric table BELOW the axes (figure coords, stable) ----
    header = ('Predictor                                      β            95% CI [low , high]               p-value        sig\n'
              '──────────────────────────────────────────────────────────────────────────────────────────────────────────────')
    rows = [header]
    def _fmt(v):
        return f'{v:+.1e}' if abs(v) < 1e-3 else f'{v:+.4f}'
    for _, row in d_plot.iterrows():
        sig = row['stars']
        try:
            pv = float(row['p'])
            pstr = 'p ≈ 0' if pv < 1e-99 else (f'{pv:.2e}' if pv < 0.0001 else f'{pv:.4f}')
        except (ValueError, TypeError):
            pstr = str(row['p'])
        rows.append(f"{row['label']:<44}  {_fmt(row['coef']):>8}    [{_fmt(row['ci_low']):>9} , {_fmt(row['ci_high']):>9}]  {pstr:>10}     {sig}")
    fig.text(0.5, 0.385, '\n'.join(rows), ha='center', va='top', fontsize=8.0, family='Consolas',
             color='#111', linespacing=1.5,
             bbox=dict(boxstyle='round,pad=0.55', facecolor='#f7f7f7', alpha=0.95,
                       edgecolor='#666', linewidth=1.0))

    how = ("How to read:  dot = point estimate β, horizontal bar = 95% CI; bar colour: green = *** (p<0.001), red = ** (p<0.01), grey = ns.  "
           "CI not crossing 0 → significant.  Advisor covariates use PRE-PROJECT windows [t-3, t-1] over the 2017-2024 OpenAlex pool; unmatched advisors = NA, not zero.\n"
           "Supervised-projects count is STRICTLY PRIOR (year < focal year; v2.0b leak fix — the earlier full-period count included future projects).  "
           "Advisor research activity BEFORE the project raises alignment (β=+0.0043, ***); supervising MANY projects lowers it (β=−0.0063, ***).  "
           "Tier dummies are ns after controlling for college context; alignment drifts up over years (β=+0.0031, ***).  "
           "Sensitivity on n=2,750 high-confidence matches gives the same signs and significance.\n"
           "[Retracted: v0.9 'recent-3y works β=+0.0085, p=4.5e-7' was a data-lineage artifact (3,712 of 3,714 values were zero).]")
    fig.text(0.5, 0.075, how, ha='center', va='top', fontsize=7.4, color='#332200',
             linespacing=1.5,
             bbox=dict(boxstyle='round,pad=0.5', facecolor='#fff7e6', alpha=0.95,
                       edgecolor='#d46b08', linewidth=1.0))
    savefig(fig, 'Figure6_HLM_Forest')

# ================================================================
# Figure 7: Transition Matrix Heatmap (Matthew Effect stability)
# ================================================================
def fig7_transition_matrix():
    inp = 'matthew_effect/transition_probabilities_year_tercile.csv'
    provenance(7, 'Supervisor Transition Matrix', inp)
    d = pd.read_csv(DATA / 'matthew_effect' / 'transition_probabilities_year_tercile.csv',
                    index_col=0)
    fig, ax = plt.subplots(figsize=(5.5, 5))
    data = d.values * 100
    im = ax.imshow(data, cmap='YlOrRd', aspect='auto', vmin=0, vmax=70)
    for i in range(3):
        for j in range(3):
            ax.text(j, i, f'{data[i,j]:.1f}%', ha='center', va='center',
                    fontsize=11, fontweight='bold',
                    color='white' if data[i,j] > 40 else 'black')
    ax.set_xticks([0, 1, 2])
    ax.set_yticks([0, 1, 2])
    ax.set_xticklabels(['Tercile 1\n(Low)', 'Tercile 2\n(Mid)', 'Tercile 3\n(High)'], fontsize=8)
    ax.set_yticklabels(['Tercile 1\n(Low)', 'Tercile 2\n(Mid)', 'Tercile 3\n(High)'], fontsize=8)
    ax.set_xlabel('To (next year)', fontweight='bold')
    ax.set_ylabel('From (current year)', fontweight='bold')
    ax.set_title('Supervisor Activity Tercile Transition Matrix\n'
                 '(n=736 consecutive pairs, diagonal = position stability)',
                 fontweight='bold', fontsize=9)
    cbar = fig.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label('Transition probability (%)', fontsize=8)
    fig.tight_layout()
    savefig(fig, 'Figure7_TransitionMatrix')

# ================================================================
# Figure 8: Diffusion Lag Histogram
# ================================================================
def fig8_diffusion_histogram():
    inp = 'diffusion_lag/diffusion_lag_histogram_bins.csv'
    provenance(8, 'Diffusion Lag Histogram', inp)
    d = pd.read_csv(DATA / 'diffusion_lag' / 'diffusion_lag_histogram_bins.csv')
    fig, ax = plt.subplots(figsize=(8, 4.5))
    colors = [COLORS['red'] if c > 0 else COLORS['green'] if c < 0 else COLORS['gray']
              for c in d['lag_year_bin_center']]
    bars = ax.bar(d['lag_year_bin_center'], d['n_topics'], color=colors, alpha=0.7,
                  edgecolor='white', linewidth=0.5, width=0.8)
    ax.axvline(x=0, color='#333', linestyle='--', linewidth=1, alpha=0.5)
    ax.set_xlabel('Lag (years): Project adoption − Paper emergence\n'
                  'Positive = research leads training (diffusion lag)',
                  fontweight='bold')
    ax.set_ylabel('Number of topics', fontweight='bold')
    # Dynamic totals from aggregate stats (single source)
    agg = pd.read_csv(DATA / 'diffusion_lag' / 'diffusion_lag_aggregate_stats.csv')
    agg_row = agg[agg['group'] == 'OVERALL'].iloc[0]
    n_lag = int(agg_row['n_topics_with_defined_lag'])
    lag_med = float(agg_row['lag_median']); lag_mean = float(agg_row['lag_mean'])
    ax.set_title(f'Diffusion Lag Distribution: Research → Training Adoption Delay\n'
                 f'({n_lag}/886 topics with defined lag, median={lag_med:.1f}, mean={lag_mean:+.2f} yr)',
                 fontweight='bold', fontsize=10)
    for bar, n, pct in zip(bars, d['n_topics'], d['pct_topics']):
        if n > 0:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                    f'{n}\n({pct:.1f}%)', ha='center', fontsize=6)
    # Legend
    legend_elements = [
        mpatches.Patch(facecolor=COLORS['red'], alpha=0.7, label='Positive lag (research → training)'),
        mpatches.Patch(facecolor=COLORS['green'], alpha=0.7, label='Negative lag (training → research)'),
        mpatches.Patch(facecolor=COLORS['gray'], alpha=0.7, label='Zero lag (synchronized)'),
    ]
    ax.legend(handles=legend_elements, loc='upper right', fontsize=7)
    fig.tight_layout()
    savefig(fig, 'Figure8_DiffusionLag')

# ================================================================
# Figure 9: Diffusion Lag by Quadrant (boxplot-style)
# ================================================================
def fig9_diffusion_by_quadrant():
    inp = 'diffusion_lag/topic_first_year_adoption.csv'
    provenance(9, 'Diffusion Lag by Quadrant (stat tables moved below axes)', inp)
    d = pd.read_csv(DATA / 'diffusion_lag' / 'topic_first_year_adoption.csv')
    d = d[d['lag_defined']].copy()
    # FROZEN DEFINITION (diffusion_lag/_build.py + audit JSON): lag uses the SINGLE-YEAR
    # non-trivial-presence rule — paper side: n_paper(y) >= 3 AND pct_paper(y) >= 0.2%
    # of that year's papers (~20+ papers in one year); project side: n_project(y) >= 2
    # AND pct_project(y) >= 0.2%. This is deliberately NOT the cumulative Top-20% quadrant
    # threshold. Empirically 0/10 LRHT and 0/698 LRLT topics ever satisfy the paper-side
    # yearly bar in 2020-2024 (expected from their low-research quadrant status; 0/708).
    # So only HRLT (24) and HRHT (5) appear as boxplots; LRHT/LRLT stay as hatched N/A panels.
    # ALL numeric stat blocks moved to a clean info panel BELOW the axes (round-6 user request).
    fig = plt.figure(figsize=(11.5, 9.6))
    ax = fig.add_axes([0.08, 0.42, 0.90, 0.48])
    quadrants_order = ['HRLT_HighResearch_LowTraining', 'HRHT_HighResearch_HighTraining',
                       'LRHT_LowResearch_HighTraining', 'LRLT_LowResearch_LowTraining']
    present_q = [q for q in quadrants_order if q in d['quadrant'].values]
    data_box = [d[d['quadrant'] == q]['lag_years'].dropna().values for q in present_q]

    n_x = 4
    quadrant_has_data = [q in present_q for q in quadrants_order]
    box_x, box_vals, box_colors = [], [], []
    data_idx = 0
    for qi, q in enumerate(quadrants_order):
        if quadrant_has_data[qi]:
            box_x.append(qi)
            box_vals.append(data_box[data_idx]); data_idx += 1
            box_colors.append(QUADRANT_COLORS[q])

    bp = ax.boxplot(box_vals, positions=box_x, widths=0.34, patch_artist=True, showmeans=True,
                    meanprops=dict(marker='D', markerfacecolor='white', markeredgecolor='#111', markersize=8),
                    medianprops=dict(color='#111', linewidth=1.8),
                    whiskerprops=dict(linewidth=1.2),
                    capprops=dict(linewidth=1.2),
                    flierprops=dict(marker='o', markersize=4, markeredgecolor='none',
                                    markerfacecolor='#888', alpha=0.6))
    for patch, color in zip(bp['boxes'], box_colors):
        patch.set_facecolor(color); patch.set_alpha(0.25); patch.set_edgecolor(color); patch.set_linewidth(1.4)

    # X-axis labels: all 4 quadrants always visible (quadrant sizes from frozen summary CSV)
    qsum = pd.read_csv(DATA / 'topic_model' / 'quadrant_overall_summary.csv')
    quadrant_total = dict(zip(qsum['quadrant'], qsum['n_topics']))
    xtick_labs = []
    for qi, q in enumerate(quadrants_order):
        nd_this = int((d['quadrant'] == q).sum())
        if quadrant_has_data[qi]:
            xtick_labs.append(f"{QUADRANT_SHORT[q]}\nn_defined = {nd_this}\n({quadrant_total[q]} in quadrant)")
        else:
            xtick_labs.append(f"{QUADRANT_SHORT[q]}\n({quadrant_total[q]} in quadrant)")

    # Jitter scatter for quadrants WITH data (no inline stat tables)
    from matplotlib.patches import Rectangle
    bp_i = 0
    stat_blocks = []  # collected for bottom panel
    rng = np.random.default_rng(7)
    for qi, q in enumerate(quadrants_order):
        if quadrant_has_data[qi]:
            vals = box_vals[bp_i]
            color = box_colors[bp_i]
            jx = rng.normal(qi, 0.045, len(vals))
            ax.scatter(jx, vals, c=color, alpha=0.9, s=46, zorder=3,
                       edgecolors='white', linewidth=0.7)
            n = len(vals); mean_v = float(np.mean(vals)); med_v = float(np.median(vals))
            q1 = float(np.percentile(vals, 25)); q3 = float(np.percentile(vals, 75))
            sd = float(np.std(vals, ddof=1))
            lo_w = float(bp['whiskers'][2*bp_i].get_ydata()[0])
            hi_w = float(bp['whiskers'][2*bp_i+1].get_ydata()[0])
            frac_pos = float(np.mean(vals > 0)) * 100
            frac_neg = float(np.mean(vals < 0)) * 100
            frac_zero = 100 - frac_pos - frac_neg
            try:
                _, p_vs0 = _stats.ttest_1samp(vals, popmean=0)
                sig0 = '***' if p_vs0 < 0.001 else '**' if p_vs0 < 0.01 else '*' if p_vs0 < 0.05 else 'ns'
            except Exception:
                p_vs0 = float('nan'); sig0 = 'na'
            stat_blocks.append(dict(short=QUADRANT_SHORT[q], color=color, n=n, mean=mean_v, sd=sd,
                                    med=med_v, sig0=sig0, p0=p_vs0, q1=q1, q3=q3,
                                    lo_w=lo_w, hi_w=hi_w, fp=frac_pos, fn=frac_neg, fz=frac_zero))
            # Small n groups: annotate the actual values so the flat boxplot is not read as "missing"
            if n <= 6:
                n_zero = int((vals == 0).sum()); n_neg = int((vals < 0).sum())
                note = f"n = {n} topics\n{n_zero} at lag 0 (synchronized)"
                if n_neg:
                    note += f"\n{n_neg} at lag {int(vals.min())} (training first)"
                ax.text(qi, 4.55, note, ha='center', va='top', fontsize=7.6, color='#333',
                        linespacing=1.4,
                        bbox=dict(boxstyle='round,pad=0.35', facecolor='white', alpha=0.85,
                                  edgecolor=color, linewidth=0.9))
            bp_i += 1
        else:
            # Undefined quadrant: clean hatched N/A PANEL (not a fake boxplot)
            ax.add_patch(Rectangle((qi - 0.42, -5.1), 0.84, 10.2,
                                   facecolor='#f4f4f4', hatch='////', edgecolor='#cfcfcf',
                                   linewidth=0.9, zorder=0.6))
            if q.startswith('LRHT'):
                na_text = ("lag undefined\nin this corpus (0/10)\n\npaper side never reaches\nnon-trivial yearly presence\n(>=3 papers & >=0.2%/yr)")
            else:
                na_text = ("lag undefined\nin this corpus (0/698)\n\nneither side reaches\nnon-trivial yearly presence\n(paper >=3 & 0.2%/yr;\nproject >=2 & 0.2%/yr)")
            ax.text(qi, 0.0, na_text, va='center', ha='center', fontsize=8.6,
                    color='#555555', fontweight='bold', linespacing=1.45, zorder=2)

    # Zero line + zone shading
    ax.axhline(y=0, color='#333', linestyle='--', linewidth=1.1, alpha=0.6, zorder=1)
    ax.axhspan(-5.5, -0.02, color=COLORS['green'], alpha=0.07, zorder=0)
    ax.axhspan(0.02, 5.5, color=COLORS['red'], alpha=0.07, zorder=0)
    ax.set_xticks(range(n_x))
    ax.set_xticklabels(xtick_labs, fontsize=9.0)
    ax.set_ylabel('Lag (years) = first year of non-trivial project presence\n'
                  '− first year of non-trivial paper presence (paper: >=3 & >=0.2%/yr; project: >=2 & >=0.2%/yr)',
                  fontweight='bold', fontsize=8.6)
    ax.set_ylim(-5.1, 5.1)
    fig.suptitle('Diffusion Lag by Quadrant  —  only HRLT & HRHT have defined lags (29/886 topics)\n'
                 'Red zone = research leads training (course update needed); green zone = training uses already-cold content.  '
                 'Statistics in panel below.',
                 fontweight='bold', fontsize=10.5, y=0.97)

    # ---- Bottom info panel (figure coords): two per-quadrant stat columns ----
    col_x = [0.28, 0.66]
    for blk, cx in zip(stat_blocks, col_x):
        block = (f"{blk['short']}  (n = {blk['n']} defined-lag topics)\n"
                 f"───────────────────────────────\n"
                 f" mean  = {blk['mean']:+.2f} yr\n"
                 f" ± SD  = {blk['sd']:.2f}\n"
                 f" med   = {blk['med']:+.1f}   (one-sample t vs 0: {blk['sig0']}, p={blk['p0']:.3f})\n"
                 f" Q1/Q3 = {blk['q1']:+.1f} / {blk['q3']:+.1f}\n"
                 f" whisk = [{blk['lo_w']:+.0f} , {blk['hi_w']:+.0f}]\n"
                 f" lag > 0 (research leads) = {blk['fp']:.0f}%\n"
                 f" lag = 0 (synchronized)   = {blk['fz']:.0f}%\n"
                 f" lag < 0 (training leads) = {blk['fn']:.0f}%")
        fig.text(cx, 0.36, block, ha='center', va='top', fontsize=8.4, family='Consolas',
                 color='#111', linespacing=1.4,
                 bbox=dict(boxstyle='round,pad=0.45', facecolor=blk['color'], alpha=0.07,
                           edgecolor=blk['color'], linewidth=1.0))

    # ---- Between-group test + retraction notice ----
    hrlts = d[d['quadrant']=='HRLT_HighResearch_LowTraining']['lag_years'].values
    hrhts = d[d['quadrant']=='HRHT_HighResearch_HighTraining']['lag_years'].values
    grp_line = ''
    if len(hrlts) > 1 and len(hrhts) > 1:
        tw, pw = _stats.ttest_ind(hrlts, hrhts, equal_var=False, alternative='two-sided')
        mw, pm = _stats.mannwhitneyu(hrlts, hrhts, alternative='two-sided')
        d_ = (np.mean(hrlts)-np.mean(hrhts))/np.sqrt((np.var(hrlts,ddof=1)+np.var(hrhts,ddof=1))/2)
        grp_line = (f"HRLT vs HRHT:  Welch t = {tw:+.2f}, p = {pw:.3f} (ns);  Mann–Whitney p = {pm:.3f} (ns);  Cohen d = {d_:+.2f} (large effect, but HRHT n=5 is underpowered)\n"
                    f"   => HRLT positive lag is larger on average (research→training direction); not significant at α=0.05 with n=5 vs 24.\n")
    how_to = (grp_line +
              "How to read: box = Q1–Q3, bold line = median, diamond = mean, whiskers = 1.5·IQR, dots = individual topics.  "
              "Lag > 0 = paper side reached non-trivial yearly presence FIRST (research leads training).  "
              "Lag < 0 = project side reached it first.\n"
              "DEFINITION (frozen): lag requires BOTH sides to show non-trivial presence in a single year "
              "(paper: >=3 docs & >=0.2% of that year's papers; project: >=2 docs & >=0.2% of that year's projects). "
              "LRHT (0/10) and LRLT (0/698) never satisfy this in the 2020-2024 corpus, so lag is undefined for them "
              "(expected from their low-research quadrant status). The old 12K-pool claim 'LRHT med = -1.5 yr' came "
              "from legacy K=307 data and is RETRACTED.")
    fig.text(0.5, 0.115, how_to, ha='center', va='top', fontsize=8.2, color='#331100',
             linespacing=1.55,
             bbox=dict(boxstyle='round,pad=0.55', facecolor='#f1f1f1', alpha=0.95,
                       edgecolor='#aa0000', linewidth=1.1))
    savefig(fig, 'Figure9_DiffusionByQuadrant')

# ================================================================
# Figure 10: Matthew Effect — Lorenz Curve + Pareto Bar
# ================================================================
def fig10_matthew_effect():
    inp = 'matthew_effect/supervisor_gini_pareto.csv'
    provenance(10, 'Matthew Effect: Lorenz + Pareto', inp)
    # Read audit JSON for Lorenz curve computation
    audit = json.loads((DATA / 'matthew_effect' / 'matthew_effect_audit.json').read_text(encoding='utf-8'))
    # Reconstruct Lorenz curve from raw project data for national-project allocation
    proj = pd.read_csv(ROOT / '01_DATA' / 'final_analysis' / 'table5_project_dataset_n3714_full.csv')
    proj['is_national'] = proj['项目等级'].astype(str).str.contains('国家级').astype(int)
    by_sup = proj.groupby('advisor').agg(n_national=('is_national', 'sum')).sort_values('n_national', ascending=False)
    vals = by_sup['n_national'].values.astype(float)
    vals_sorted = np.sort(vals)
    n = len(vals_sorted)
    cum = np.cumsum(vals_sorted)
    total = cum[-1] if cum[-1] > 0 else 1
    lorenz_y = np.concatenate([[0], cum / total])
    lorenz_x = np.arange(n + 1) / n

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 5))
    # Left: Lorenz curve
    ax1.plot(lorenz_x, lorenz_y, color=COLORS['red'], linewidth=2, label=f'National grants (Gini={audit["gini"]["value_national_projects"]:.3f})')
    ax1.plot([0, 1], [0, 1], '--', color=COLORS['gray'], linewidth=1, label='Perfect equality')
    ax1.fill_between(lorenz_x, lorenz_x, lorenz_y, alpha=0.1, color=COLORS['red'])
    ax1.set_xlabel('Cumulative share of supervisors (sorted)', fontweight='bold')
    ax1.set_ylabel('Cumulative share of national projects', fontweight='bold')
    ax1.set_title('Lorenz Curve: National Project Allocation Inequality\n'
                  '(Gini = 0.767, Top 5% hold 34.0%)', fontweight='bold', fontsize=9)
    ax1.legend(fontsize=8)

    # Right: Pareto bar
    pareto_data = audit['gini']['pareto_national_shares_pct']
    pcts = ['top1', 'top5', 'top10', 'top20', 'top50']
    vals_p = [pareto_data.get(f'{p}_national_share_pct', 0) for p in pcts]
    bars = ax2.bar(pcts, vals_p, color=[COLORS['red'], COLORS['orange'], COLORS['orange'],
                                         COLORS['blue'], COLORS['gray']], alpha=0.8, width=0.6)
    ax2.axhline(y=5, color='#999', linestyle='--', linewidth=0.8, label='Equal share line')
    for bar, v in zip(bars, vals_p):
        ax2.text(bar.get_x() + bar.get_width()/2, v + 1, f'{v:.1f}%', ha='center', fontsize=8, fontweight='bold')
    ax2.set_xlabel('Top N% supervisors', fontweight='bold')
    ax2.set_ylabel('Share of national projects (%)', fontweight='bold')
    ax2.set_title('Pareto Distribution of National Projects\n'
                  '(Top 20% supervisors hold 76.8%)', fontweight='bold', fontsize=9)
    ax2.legend(fontsize=8)
    fig.tight_layout()
    savefig(fig, 'Figure10_MatthewEffect')

# ================================================================
# Figure 11: Quadrant Summary Grouped Bars
# ================================================================
def fig11_quadrant_summary():
    inp = 'topic_model/quadrant_overall_summary.csv'
    provenance(11, 'Quadrant Summary Bars', inp)
    d = pd.read_csv(DATA / 'topic_model' / 'quadrant_overall_summary.csv')
    d = d.sort_values('quadrant')
    fig, axes = plt.subplots(1, 3, figsize=(11, 4))
    # Subplot 1: n_topics
    colors = [QUADRANT_COLORS.get(q, COLORS['gray']) for q in d['quadrant']]
    short_labels = [QUADRANT_SHORT.get(q, q) for q in d['quadrant']]
    axes[0].bar(short_labels, d['n_topics'], color=colors, alpha=0.8, width=0.6)
    for i, v in enumerate(d['n_topics']):
        axes[0].text(i, v + 2, str(v), ha='center', fontweight='bold', fontsize=9)
    axes[0].set_ylabel('Number of topics', fontweight='bold')
    axes[0].set_title('Topic count', fontweight='bold')

    # Subplot 2: n_papers
    axes[1].bar(short_labels, d['n_papers_total'], color=colors, alpha=0.8, width=0.6)
    for i, v in enumerate(d['n_papers_total']):
        axes[1].text(i, v + 50, str(v), ha='center', fontweight='bold', fontsize=9)
    axes[1].set_ylabel('Number of papers', fontweight='bold')
    axes[1].set_title('Paper documents', fontweight='bold')

    # Subplot 3: n_projects
    axes[2].bar(short_labels, d['n_projects_total'], color=colors, alpha=0.8, width=0.6)
    for i, v in enumerate(d['n_projects_total']):
        axes[2].text(i, v + 15, str(v), ha='center', fontweight='bold', fontsize=9)
    axes[2].set_ylabel('Number of projects', fontweight='bold')
    axes[2].set_title('Project documents', fontweight='bold')

    fig.suptitle('Four-Quadrant Topic Summary: Research-Training Alignment Landscape',
                 fontweight='bold', fontsize=11, y=1.02)
    fig.tight_layout()
    savefig(fig, 'Figure11_QuadrantSummary')

# ================================================================
# Figure 12: College RTAS Ranking (Top 20 + Bottom 5, fontsize=10)
# ================================================================
def fig12_college_rtas_ranking():
    inp = 'heterogeneity/college_rtas_summary_all.csv'
    provenance(12, 'College RTAS Full Ranking (All 40, Appendix)', inp)
    d = pd.read_csv(DATA / 'heterogeneity' / 'college_rtas_summary_all.csv')
    d = d.sort_values('rtas_mean')  # ascending for horizontal bar (rank 40 top → rank 1 bottom)
    d['college_en'] = d['college'].apply(translate_college)
    n_all = len(d)
    fig, ax = plt.subplots(figsize=(9, max(10, 0.32 * n_all + 2)))
    # Color mapped to VALUE (same normalization language as Figure 5)
    norm = plt.Normalize(vmin=d['rtas_mean'].min(), vmax=d['rtas_mean'].max())
    cmap = plt.cm.RdYlGn  # red = low RTAS, green = high RTAS
    colors = cmap(norm(d['rtas_mean'].values))
    bars = ax.barh(range(n_all), d['rtas_mean'], color=colors,
                   edgecolor='white', linewidth=0.3, height=0.7)
    ax.set_yticks(range(n_all))
    # Ascending = lowest RTAS on top (most-worst → #40 at top), highest RTAS at bottom (#1 at bottom).
    # Use "N.  Name" format (no hash) per user request. rank column already holds 1..40 (1=best).
    rank_labels = [f"{int(r)}.  {name}" for r, name in zip(d['rank'], d['college_en'])]
    ax.set_yticklabels(rank_labels, fontsize=8)
    ax.set_xlabel('RTAS (mean)', fontweight='bold')
    ax.set_title(f'All {n_all} Colleges by RTAS — Full Ranking (Appendix)\n'
                 'College ANOVA: F(38,3674)=195.45, p≈0, η²=66.90%',
                 fontweight='bold', fontsize=10)
    for i, (val, n) in enumerate(zip(d['rtas_mean'], d['n_projects'])):
        ax.text(val + 0.003, i, f'{val:.3f} (n={n})', va='center', fontsize=6.5)
    ax.set_xlim(0, max(d['rtas_mean']) * 1.25)
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    cbar = fig.colorbar(sm, ax=ax, shrink=0.5, pad=0.12)
    cbar.set_label('RTAS color scale:  red = lower alignment  →  green = higher alignment', fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    fig.tight_layout()
    savefig(fig, 'FigureS1_CollegeRTAS_Full40', subdir='supp')

# ================================================================
# Figure 13: Topic Yearly Prevalence Stacked Area (boundary_fontsize=6)
# ================================================================
def fig13_stacked_area():
    inp = 'topic_model/topic_yearly_prevalence_for_diffusion_lag.csv + topic_model/topic_info.csv (topic words)'
    provenance(13, 'Topic Yearly Stacked Area — Top-15 mainstream topics; top legend box explains band meanings', inp)
    import matplotlib.patheffects as pe
    d = pd.read_csv(DATA / 'topic_model' / 'topic_yearly_prevalence_for_diffusion_lag.csv')
    ti = pd.read_csv(DATA / 'topic_model' / 'topic_info.csv')
    # Pivot: year × topic → pct_project (project-side adoption over time)
    pivot = d.pivot_table(index='year', columns='topic_id', values='pct_project', fill_value=0)
    # Top-15 mainstream topics only. The remaining 871 long-tail topics (~29-33% of
    # projects, a flat heterogeneous "Other" mass) are EXCLUDED so the mainstream
    # bands fill the plot area and boundary labels stay readable.
    top_topics = pivot.sum().nlargest(15).index
    pivot_top = pivot[top_topics].copy()
    other_share = pivot.drop(columns=top_topics).sum(axis=1)
    band_ids = [int(c) for c in pivot_top.columns]
    band_vals = [pivot_top[c].values for c in pivot_top.columns]
    top15_total = pivot_top.sum(axis=1)

    # --- Topic meaning labels: curated short English glosses of c-TF-IDF top words ---
    # (words verified from topic_info.csv Name/Representation; long-tail topics fall
    # back to auto-parsed English tokens from the same frozen file)
    TOPIC_GLOSS = {
        5:   'Language learning (Chinese/English)',
        72:  'Robots / robotics',
        125: 'Drones / unmanned vehicles',
        22:  'Dental implants',
        216: 'Online learning / big data',
        6:   'Urban land / ecology',
        160: 'College English / talent education',
        429: 'Internet platforms & legal governance',
        333: 'Event cameras / imagers',
        3:   'Blockchain / privacy computing',
        196: 'Deep learning',
        140: 'Food safety',
        2:   'Lithium-ion batteries',
        345: 'Elderly care / aging',
        81:  'Video quality / coding',
    }
    def auto_gloss(tid):
        row = ti.loc[ti['Topic'] == tid, 'Name']
        if len(row) == 0:
            return f'Topic {tid}'
        toks = [t for t in str(row.iloc[0]).split('_')[1:] if t.isascii() and t.isalpha()]
        seen = []
        for t in toks:
            if t not in seen:
                seen.append(t)
        return ' '.join(seen[:3]) if seen else f'Topic {tid}'
    band_gloss = [TOPIC_GLOSS.get(t, auto_gloss(t)) for t in band_ids]

    # --- Layout: figure height unchanged; plot deliberately VERY FLAT (30% of height,
    # half of the previous 60% per user request) so the top ~60% holds the framed
    # legend box explaining what each colour means.
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_axes([0.075, 0.105, 0.905, 0.30])
    colors = plt.cm.tab20(np.linspace(0, 1, len(band_ids)))
    stacks = ax.stackplot(pivot_top.index, *band_vals, colors=colors, alpha=0.82)

    # --- Dots + cumulative value at EVERY band's UPPER edge, at EVERY year ---
    years = pivot_top.index.values
    cum = np.zeros(len(years))
    halo = [pe.withStroke(linewidth=1.8, foreground='white')]
    for k, vals in enumerate(band_vals):
        cum = cum + np.asarray(vals)
        for yi, yr in enumerate(years):
            yv = cum[yi]
            ax.plot(yr, yv, 'o', ms=2.9, zorder=6,
                    markerfacecolor='#222', markeredgecolor='white', markeredgewidth=0.6)
            ax.text(yr + 0.045, yv, f'{yv:.1f}', ha='left', va='center',
                    fontsize=6.0, color='#111', zorder=7, path_effects=halo, family='Consolas')

    ax.set_xlabel('Year', fontweight='bold', fontsize=11)
    ax.set_ylabel('Cumulative project-side prevalence (%)',
                  fontweight='bold', fontsize=9.5)
    ax.set_xticks(years)
    ax.set_xticklabels(years, fontsize=10)
    ax.set_ylim(0, None)
    ax.margins(x=0.075)

    # Top-15 total per year (top of the last band) — bold label
    ymax = float(top15_total.max())
    for yi, yr in enumerate(years):
        total = float(top15_total.iloc[yi])
        ax.text(yr, total + ymax * 0.04, f'Top-15 total {total:.1f}%', ha='center', fontsize=8.5,
                fontweight='bold', color='#333', path_effects=halo)

    # --- Top framed legend box: colour → topic MEANING (c-TF-IDF gloss) ---
    handles = [plt.Rectangle((0, 0), 1, 1, facecolor=c, alpha=0.82, edgecolor='white') for c in colors]
    labels = [f'T{tid}: {g}' for tid, g in zip(band_ids, band_gloss)]
    leg = fig.legend(handles, labels, loc='upper center', bbox_to_anchor=(0.5, 0.875),
                     ncol=3, fontsize=9.5, frameon=True, fancybox=True,
                     edgecolor='#777777', borderpad=1.0, labelspacing=1.1,
                     columnspacing=1.8, handlelength=1.6, handletextpad=0.6,
                     title='What each colour band is  (c-TF-IDF top words; legend order = bottom → top stacking order)',
                     title_fontsize=10)
    leg.get_frame().set_facecolor('#fafafa')
    fig.text(0.5, 0.985, 'Mainstream Topic Prevalence in Projects Over Time (Top 15 topics only; the other 871 long-tail topics are excluded)',
             ha='center', va='top', fontsize=13, fontweight='bold')

    # Footnote: excluded Other share per year
    foot = 'Excluded "Other" (871 remaining long-tail topics): ' + \
           ' / '.join(f'{int(yr)}: {float(other_share.iloc[yi]):.1f}%' for yi, yr in enumerate(years))
    fig.text(0.5, 0.02, foot, ha='center', va='bottom', fontsize=8, color='#555', style='italic')
    savefig(fig, 'Figure13_TopicStackedArea')

# ================================================================
# MAIN
# ================================================================
if __name__ == '__main__':
    print(f'[10_generate_figures] v{CFG["version"]}  DPI={DPI}')
    print(f'  Output main: {OUT_MAIN}')
    print(f'  Output supp: {OUT_SUPP}')
    print(f'  CJK font: {CJK_FONT}')
    print()
    print('Generating all figures from frozen 03_FINAL_ANALYSIS CSVs...')
    print()

    fig2_roadmap()
    fig3_quadrant_scatter()
    fig4_project_level()
    fig5_top20_colleges()
    fig6_hlm_forest()
    fig7_transition_matrix()
    fig8_diffusion_histogram()
    fig9_diffusion_by_quadrant()
    fig10_matthew_effect()
    fig11_quadrant_summary()
    fig12_college_rtas_ranking()
    fig13_stacked_area()

    print()
    print(f'[10_generate_figures] DONE. {len(list(OUT_MAIN.glob("*.pdf")))} PDF + '
          f'{len(list(OUT_MAIN.glob("*.png")))} PNG files in {OUT_MAIN}')
