# -*- coding: utf-8 -*-
"""
10_generate_figures.py  —  SINGLE ENTRY POINT for all final manuscript figures.
================================================================================
RULE (enforced, per FINAL_ANALYSIS_PROTOCOL §4):
  Every figure generated by the project must have a 1-line PROVENANCE comment:
    # Figure X <Short title>  <--  input.csv --(10_generate_figures.py)--> FigureX_xxx.pdf
  No figure in 05_FINAL_FIGURES/ is ever hand-copied from a historical folder.

Output: PDF (vector) + 600 dpi PNG into 05_FINAL_FIGURES/main/ and supplementary/.
NO "Fig X" text inside any image canvas (config policy).

Figures generated (v1.0-cand.5 final freeze — 7 main + 4 supplementary):
  MAIN (7):
  Figure 2  Technical Roadmap      <-- FINAL_ANALYSIS_PROTOCOL §2 (rho_s=.405 in Embedding box; Heterogeneity fed from RTAS Frozen, not raw corpus) --(10_generate_figures.py)--> Figure2_Roadmap.pdf
  Figure 3  4-Quadrant Scatter     <-- topic_info.csv (zoom inset + bubble legend) --(10_generate_figures.py)--> Figure3_QuadrantScatter.pdf
  Figure 4  Project-Level Dist.    <-- project_level_summary.csv + table5_project_dataset_n3714_full.csv (box+jitter; ex-Fig4b; old 4a DELETED as redundant) --(10_generate_figures.py)--> Figure4_Distribution.pdf
  Figure 5  College Caterpillar    <-- hlm_v2b_college_random_effects.csv (BLUPs, ICC=0.738) --(10_generate_figures.py)--> Figure5_CollegeCaterpillar.pdf
  Figure 6  HLM Forest Plot        <-- hlm_mixedlm_v2b_primary_coefficients.csv (SAME source as Table 6; sig defs moved to caption) --(10_generate_figures.py)--> Figure6_HLM_Forest.pdf
  Figure 8  Diffusion-Lag split    <-- diffusion_lag_histogram_bins.csv + topic_first_year_adoption.csv (v1.0-cand.6 split into TWO files: 8a legend outside-right; 8b red-border value box DELETED, taller canvas) --(10_generate_figures.py)--> Figure8a_LagDistribution.pdf + Figure8b_LagByQuadrant.pdf
  Figure 10 Matthew 3-panel        <-- supervisor_gini_pareto.csv + lagged_logit_national_path_dependence*.csv (panel c "Expanded risk set"; v1.0-cand.6 top50 100% gray bar removed, wspace widened) --(10_generate_figures.py)--> Figure10_MatthewEffect.pdf
  SUPPLEMENTARY (4):
  Figure S1 College Full Ranking   <-- college_rtas_summary_all.csv (p < .001, not p≈0) --(10_generate_figures.py)--> supplementary/FigureS1_CollegeRTAS_Full40.pdf
  Figure 7  Transition Matrix      <-- transition_probabilities_year_tercile.csv --(10_generate_figures.py)--> supplementary/Figure7_TransitionMatrix.pdf
  Figure 11 Quadrant Summary       <-- quadrant_overall_summary.csv (clustered denominators) --(10_generate_figures.py)--> supplementary/Figure11_QuadrantSummary.pdf
  Figure 13 Topic Dynamics 2-panel <-- topic_yearly_prevalence_for_diffusion_lag.csv (denominator = ALL projects/yr, sum(denom_project)=3,714; demoted to Supplementary) --(10_generate_figures.py)--> supplementary/Figure13_TopicDynamics.pdf
  DELETED (v1.0-cand.5): Figure4a_MeanCI (redundant with Fig4 mean diamonds), FigureS2_Top20Colleges (raw-mean small-n amplification; caterpillar + S1 suffice).
"""
from __future__ import annotations
import os, sys, json, re, warnings; warnings.filterwarnings('ignore')
from pathlib import Path

import yaml
import numpy as np
import pandas as pd
from scipy import stats as _stats  # Welch t / Mann-Whitney for boxplot pairwise stars
import matplotlib
matplotlib.use('Agg')  # non-interactive backend
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.gridspec as gridspec

# ================================================================
# 0. Global style configuration
# ================================================================
ROOT = Path(__file__).resolve().parents[1]
CFG = yaml.safe_load((ROOT / '00_README' / 'final_config.yaml').read_text(encoding='utf-8'))
VCFG = CFG.get('visualization', {})
DPI = int(VCFG.get('png_dpi', 600))
OUT_MAIN = ROOT / VCFG.get('output_main', '05_FINAL_FIGURES/main/')
OUT_SUPP = ROOT / VCFG.get('output_supp', '05_FINAL_FIGURES/supplementary/')
OUT_MAIN.mkdir(parents=True, exist_ok=True)
OUT_SUPP.mkdir(parents=True, exist_ok=True)

# CJK font setup for Chinese college names
for font in ['Microsoft YaHei', 'SimHei', 'Noto Sans CJK SC', 'Arial Unicode MS']:
    try:
        matplotlib.font_manager.findfont(font, fallback_to_default=False)
        CJK_FONT = font
        break
    except Exception:
        continue
else:
    CJK_FONT = 'SimHei'

plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': [CJK_FONT, 'DejaVu Sans', 'Arial'],
    'axes.unicode_minus': False,
    'figure.dpi': 100,
    'savefig.dpi': DPI,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.15,
    'font.size': 9,
    'axes.titlesize': 11,
    'axes.labelsize': 10,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'legend.fontsize': 8,
    'axes.spines.top': False,
    'axes.spines.right': False,
    'axes.grid': True,
    'grid.alpha': 0.3,
    'grid.linestyle': '--',
})

# Color palette (serious, publication-quality)
COLORS = {
    'blue':   '#2E5C8A',
    'red':    '#C0392B',
    'green':  '#27AE60',
    'orange': '#E67E22',
    'purple': '#7D3C98',
    'gray':   '#7F8C8D',
    'teal':   '#1ABC9C',
    'navy':   '#1A237E',
}
QUADRANT_COLORS = {
    'HRHT_HighResearch_HighTraining': '#C0392B',  # red — both high
    'HRLT_HighResearch_LowTraining':  '#E67E22',  # orange — research leads
    'LRHT_LowResearch_HighTraining':  '#27AE60',  # green — training leads
    'LRLT_LowResearch_LowTraining':   '#7F8C8D',  # gray — both low
}
QUADRANT_SHORT = {
    'HRHT_HighResearch_HighTraining': 'HRHT',
    'HRLT_HighResearch_LowTraining':  'HRLT',
    'LRHT_LowResearch_HighTraining': 'LRHT',
    'LRLT_LowResearch_LowTraining':   'LRLT',
}

# Chinese college name → English translation (for ALL-English figure policy)
COLLEGE_EN = {
    '中国南极测绘研究中心': 'Chinese Antarctic Center for Surveying & Mapping',
    '化学与分子科学学院': 'College of Chemistry & Molecular Sciences',
    '工业科学研究院': 'Institute of Industrial Science',
    '测绘遥感信息工程国家重点实验室': 'State Key Lab of Info. Eng. in Surveying & Remote Sensing',
    '国家网络安全学院': 'School of Cyber Science',
    '遥感信息工程学院': 'School of Remote Sensing & Info. Engineering',
    '计算机学院': 'School of Computer Science',
    '水利水电学院': 'College of Water Resources & Hydropower',
    '物理科学与技术学院': 'School of Physics & Technology',
    '电子信息学院': 'School of Electronic Information',
    '电气与自动化学院': 'School of Electrical Engineering & Automation',
    '资源与环境科学学院': 'School of Resource & Environmental Sciences',
    '城市设计学院': 'School of Urban Design',
    '土木建筑工程学院': 'School of Civil & Architectural Engineering',
    '动力与机械学院': 'School of Power & Mechanical Engineering',
    '数学与统计学院': 'School of Mathematics & Statistics',
    '生命科学学院': 'College of Life Sciences',
    '经济与管理学院': 'School of Economics & Management',
    '信息管理学院': 'School of Information Management',
    '新闻与传播学院': 'School of Journalism & Communication',
    '政治与公共管理学院': 'School of Political Science & Public Management',
    '法学院': 'Law School',
    '文学院': 'School of Chinese Language & Literature',
    '哲学学院': 'School of Philosophy',
    '历史学院': 'School of History',
    '外国语言文学学院': 'School of Foreign Languages & Literature',
    '艺术与设计学院': 'School of Arts & Design',
    '艺术学院': 'School of Arts',
    '第一临床学院': 'First Clinical College',
    '第二临床学院': 'Second Clinical College',
    '基础医学院': 'School of Basic Medical Sciences',
    '口腔医学院': 'School of Stomatology',
    '公共卫生学院': 'School of Public Health',
    '药学院': 'School of Pharmaceutical Sciences',
    '护理学院': 'School of Nursing',
    '健康学院': 'School of Health',
    '印刷与包装系': 'Dept. of Printing & Packaging',
    '弘毅学堂': 'Hongyi College',
    '马克思主义学院': 'School of Marxism',
    '测绘学院': 'School of Geodesy & Geomatics',
    '国际教育学院': 'School of International Education',
}
def translate_college(name):
    """Translate Chinese college name to English; return original if not found."""
    return COLLEGE_EN.get(str(name).strip(), str(name).strip())

# Data root
DATA = ROOT / '03_FINAL_ANALYSIS'

def savefig(fig, name, subdir='main'):
    """Save figure as PDF + PNG with provenance."""
    out_dir = OUT_MAIN if subdir == 'main' else OUT_SUPP
    pdf_path = out_dir / f'{name}.pdf'
    png_path = out_dir / f'{name}.png'
    fig.savefig(pdf_path, format='pdf', dpi=DPI)
    fig.savefig(png_path, format='png', dpi=DPI)
    plt.close(fig)
    print(f'  ✓ {name}.pdf + {name}.png  →  {out_dir}')

def provenance(fig_num, title, input_csv, script='10_generate_figures.py'):
    """Print provenance line."""
    print(f'# Figure {fig_num} {title}  <--  {input_csv} --({script})--> see output files')

# ================================================================
# Figure 2: Technical Roadmap (schematic)
# ================================================================
def fig2_roadmap():
    provenance(2, 'Technical Roadmap (dual-corpus)', 'FINAL_ANALYSIS_PROTOCOL.md §2')
    fig, ax = plt.subplots(figsize=(11.5, 7.0))
    ax.set_xlim(0, 11.5); ax.set_ylim(0, 7.0); ax.axis('off')

    # v1.0-cand.4 reviewer-audit redesign:
    #   1) TWO corpora are now explicit (main RTAS corpus 2020-2024 vs auxiliary
    #      advisor-history corpus 2017-2019 that only feeds HLM pre-project covariates);
    #   2) pairwise semantic validity rho=.405 moved to the EMBEDDING box (it is
    #      embedding-level and shared by all 5 aggregation variants);
    #   3) RTAS Frozen box now shows variant SELECTION (5 variants, mean chosen by
    #      composite score .742) instead of the validity number;
    #   4) RI-CLPM "future work" box REMOVED from the method figure (never estimated).
    BW2, BH2 = 2.4, 1.15        # standard box size
    boxes = [
        # Row 1 (y=5.4): the two corpora
        (0.60, 5.40, 5.20, 1.15, 'Main RTAS corpus\n3,714 ITTP projects (CN)  +  56,901 OpenAlex papers (EN)\nOpenAlex 2020-2024', COLORS['blue']),
        (6.30, 5.40, 4.60, 1.15, 'Auxiliary advisor-history corpus\n22,438 OpenAlex papers, 2017-2019\n-> pre-project covariate windows [t-3, t-1]', None),
        # Row 2 (y=3.45): method pipeline
        (0.60, 3.45, BW2, BH2, 'Embedding\nMultilingual MiniLM\nL12-v2 (384-dim)\nPairwise semantic validity\n$\\rho_s$ = .405 (n=150, p=2.6e-7)', COLORS['teal']),
        (3.40, 3.45, BW2, BH2, 'RTAS Computation\nCosine similarity\nMean aggregation\nCumulative [2020, t]', COLORS['green']),
        (6.30, 3.45, BW2, BH2, 'RTAS Frozen\n5 aggregation variants\ntested; Primary = mean\n(composite score .742)', COLORS['navy']),
        # Row 3 (y=1.50): analyses (v1.0-cand.5: BERTopic moved to the LEFTMOST slot,
        #   directly under Embedding, so the embeddings branch feeds it with a straight
        #   vertical; the three RTAS-fed analyses (Het/Matthew/HLM) all hang off RTAS
        #   Frozen. Left column = text-mining branch, right columns = RTAS analyses.)
        (3.40, 1.50, BW2, BH2, 'Heterogeneity (RQ1)\nF(2,3711)=35.7\neta2=1.89%\nd=0.352', COLORS['blue']),
        (0.60, 1.50, BW2, BH2, 'BERTopic (RQ2)\nUMAP+HDBSCAN\nK=886 topics\n4-quadrant', COLORS['orange']),
        (6.30, 1.50, BW2, BH2, 'Matthew (RQ4)\nGini=0.767\nTop5%=34.0%\nlag-OR=2.25***', COLORS['red']),
        (9.10, 1.50, BW2, BH2, 'HLM (RQ3)\nMixedLM RE\nICC=0.738, 39 colleges\nclean prior supervision', COLORS['purple']),
        # Row 4 (y=0.05): downstream
        (3.40, 0.05, BW2, 1.00, 'Diffusion Lag (RQ2)\n29/886 defined\nHRLT median +0.5 yr', COLORS['gray']),
    ]
    edges = {}
    for x, y, w, h, text, color in boxes:
        aux = color is None
        rect = mpatches.FancyBboxPatch((x, y), w, h, boxstyle='round,pad=0.07',
                                        facecolor=('#f2f2f2' if aux else color),
                                        alpha=(0.9 if aux else 0.13),
                                        edgecolor=('#888888' if aux else color),
                                        linewidth=1.4, linestyle=('--' if aux else '-'))
        ax.add_patch(rect)
        ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=6.4, fontweight='bold',
                color=('#444444' if aux else color), linespacing=1.4)
        edges[(x, y, w, h)] = {
            'top': (x + w/2, y + h), 'bottom': (x + w/2, y),
            'left': (x, y + h/2), 'right': (x + w, y + h/2),
            'bottom_left': (x + w*0.25, y), 'bottom_right': (x + w*0.75, y),
            'top_left': (x + w*0.25, y + h), 'top_right': (x + w*0.75, y + h),
        }

    def arrow(p1, p2, dashed=False, rad=0.0):
        ax.annotate('', xy=p2, xytext=p1,
                    arrowprops=dict(arrowstyle='->', color='#555555', lw=1.2,
                                    linestyle=('--' if dashed else '-'),
                                    connectionstyle=f'arc3,rad={rad}'),
                    zorder=1)

    def elbow(p1, p2, y_mid):
        """Orthogonal 3-segment connector (v1.0-cand.5): vertical from p1 to the
        inter-row highway at y_mid, horizontal to p2.x, then arrowhead into p2.
        Keeps Row2->Row3 data flow in separate lanes (no diagonal crossings)."""
        ax.plot([p1[0], p1[0]], [p1[1], y_mid], color='#555555', lw=1.2, zorder=1)
        ax.plot([p1[0], p2[0]], [y_mid, y_mid], color='#555555', lw=1.2, zorder=1)
        ax.annotate('', xy=p2, xytext=(p2[0], y_mid),
                    arrowprops=dict(arrowstyle='->', color='#555555', lw=1.2), zorder=1)

    b = [bb[:4] for bb in boxes]
    main, aux, emb, comp, froz = b[0], b[1], b[2], b[3], b[4]
    het, bert, mat, hlm, diff = b[5], b[6], b[7], b[8], b[9]
    # Row 1 -> Row 2: main corpus feeds embedding; aux corpus feeds HLM covariates
    arrow(edges[main]['bottom_left'], edges[emb]['top'])            # main corpus -> embedding
    arrow(edges[aux]['bottom_right'], edges[hlm]['top_right'], dashed=True)  # aux corpus -> HLM
    # Row 2 horizontal pipeline
    arrow(edges[emb]['right'], edges[comp]['left'])
    arrow(edges[comp]['right'], edges[froz]['left'])
    # Row 2 -> Row 3 (v1.0-cand.5 rerouting): analyses consume FROZEN RTAS or the
    # frozen embeddings, never the raw corpus. BERTopic now sits in the leftmost
    # column directly under Embedding (straight vertical feed); Heterogeneity /
    # Matthew / HLM are fed from RTAS Frozen -> data flow is crossing-free.
    arrow(edges[emb]['bottom'], edges[bert]['top'])                  # embeddings -> BERTopic (vertical, same column)
    elbow(edges[froz]['bottom'], edges[het]['top'], y_mid=3.05)      # frozen RTAS -> Heterogeneity (was: raw corpus -> Het)
    arrow(edges[froz]['bottom_right'], edges[mat]['top_right'])      # frozen RTAS -> Matthew (vertical drop)
    arrow(edges[froz]['right'], edges[hlm]['top_left'])              # frozen RTAS -> HLM
    # Row 3 -> Row 4
    elbow(edges[bert]['bottom'], edges[diff]['top'], y_mid=1.25)     # BERTopic -> Diffusion Lag

    ax.set_title('RTAS Technical Roadmap — Dual-Corpus Data to Discovery',
                 fontsize=12, fontweight='bold', pad=10)
    fig.tight_layout()
    savefig(fig, 'Figure2_Roadmap')

# ================================================================
# Figure 3: 4-Quadrant Scatter (individual topics)
# ================================================================
def fig3_quadrant_scatter():
    inp = 'topic_model/topic_info.csv'
    provenance(3, '4-Quadrant Scatter (zoom inset + bubble size legend)', inp)
    ti = pd.read_csv(DATA / 'topic_model' / 'topic_info.csv')
    ti = ti[ti['Topic'] >= 0].copy()  # exclude outlier row
    fig, ax = plt.subplots(figsize=(8, 6.8))
    for q, color in QUADRANT_COLORS.items():
        sub = ti[ti['quadrant'] == q]
        if len(sub) == 0: continue
        ax.scatter(sub['frac_paper'] * 100, sub['frac_project'] * 100,
                   s=sub['Count'] * 0.3, c=color, alpha=0.6, edgecolors='white', linewidth=0.3,
                   label=f'{QUADRANT_SHORT[q]} (n={len(sub)})', zorder=3)
    # Threshold lines
    thr_p = ti['thr_paper_pct_used'].iloc[0] if 'thr_paper_pct_used' in ti.columns else 0.31
    thr_r = ti['thr_project_pct_used'].iloc[0] if 'thr_project_pct_used' in ti.columns else 0.5
    ax.axhline(y=thr_r, color='#999999', linestyle='--', linewidth=0.8, alpha=0.5)
    ax.axvline(x=thr_p, color='#999999', linestyle='--', linewidth=0.8, alpha=0.5)
    # Force BOTH axes to start exactly at 0 so the single origin (0,0) is the
    # bottom-left corner where the x-0 and y-0 ticks coincide (no floating 0 ticks).
    xmax = float((ti['frac_paper'] * 100).max())
    ymax = float((ti['frac_project'] * 100).max())
    ax.set_xlim(0, xmax * 1.06)
    ax.set_ylim(0, ymax * 1.12)
    ax.set_xlabel('Paper Prevalence (%)', fontweight='bold')
    ax.set_ylabel('Project Prevalence (%)', fontweight='bold')
    ax.set_title('Topic Distribution across Research-Training Quadrants', fontweight='bold')

    # v1.0-cand.4 reviewer audit: (1) zoomed inset over the crowded origin so the
    # 698 LRLT + small-topic mass becomes legible; (2) bubble-size reference legend
    # (bubble area encodes topic documents via s = Count * 0.3).
    # Inset is kept NARROW (right edge ~0.90 axes-fraction) so the extreme HRHT
    # topic near x=1.47% stays visible in the main axes.
    axins = ax.inset_axes([0.53, 0.42, 0.375, 0.53])
    for q, color in QUADRANT_COLORS.items():
        sub = ti[ti['quadrant'] == q]
        if len(sub) == 0: continue
        axins.scatter(sub['frac_paper'] * 100, sub['frac_project'] * 100,
                      s=sub['Count'] * 0.3, c=color, alpha=0.65, edgecolors='white',
                      linewidth=0.3, zorder=3)
    axins.axhline(y=thr_r, color='#999999', linestyle='--', linewidth=0.8, alpha=0.5)
    axins.axvline(x=thr_p, color='#999999', linestyle='--', linewidth=0.8, alpha=0.5)
    axins.set_xlim(0, 0.25)
    axins.set_ylim(0, 1.2)
    axins.tick_params(labelsize=6)
    axins.set_title('Zoom: origin cluster (0-0.25%, 0-1.2%)', fontsize=7.5, fontweight='bold')
    axins.grid(alpha=0.2, linewidth=0.4)
    ax.indicate_inset_zoom(axins, edgecolor='#666666', alpha=0.8)

    # Quadrant labels — anchored INSIDE the true quadrant regions relative to the
    # threshold lines (HRHT label moved below the inset window, which occupies the
    # upper-right corner).
    ytop = ax.get_ylim()[1]; xright = ax.get_xlim()[1]
    import matplotlib.patheffects as _pe3
    _halo3 = [_pe3.withStroke(linewidth=2.2, foreground='white')]
    def _qlabel(x, y, txt, color, alpha):
        ax.text(x, y, txt, ha='left', fontsize=9, color=color, alpha=alpha,
                fontweight='bold', path_effects=_halo3, zorder=5)
    _qlabel(xright * 0.80, ytop * 0.36, 'HRHT', QUADRANT_COLORS['HRHT_HighResearch_HighTraining'], 0.55)
    _qlabel(0.015, ytop * 0.88, 'LRHT', QUADRANT_COLORS['LRHT_LowResearch_HighTraining'], 0.75)
    _qlabel(xright * 0.58, thr_r * 0.35, 'HRLT', QUADRANT_COLORS['HRLT_HighResearch_LowTraining'], 0.6)
    _qlabel(0.012, thr_r * 0.62, 'LRLT', QUADRANT_COLORS['LRLT_LowResearch_LowTraining'], 0.9)

    # Two legends on one axes (matplotlib multi-legend pattern): create the
    # quadrant legend, then the size legend (which replaces ax.legend_), then
    # RE-ADD the quadrant legend as an artist — otherwise the second ax.legend()
    # call silently deletes the first legend.
    quad_leg = ax.legend(loc='upper center', bbox_to_anchor=(0.40, -0.135), ncol=2,
                         framealpha=0.9, fontsize=7.5)
    # Bubble-size reference legend inside the gap between LRHT label and inset
    size_handles = [ax.scatter([], [], s=n_docs * 0.3, facecolors='none',
                               edgecolors='#666666', linewidth=1.0)
                    for n_docs in (25, 100, 500)]
    size_leg = ax.legend(size_handles, ['25 docs', '100 docs', '500 docs'],
                         title='Bubble size = topic documents',
                         loc='upper left', bbox_to_anchor=(0.245, 1.0),
                         fontsize=6.5, title_fontsize=7, framealpha=0.9,
                         labelspacing=1.0, borderpad=0.6, handletextpad=0.9)
    ax.add_artist(quad_leg)
    ax.add_artist(size_leg)
    # Reserve bottom margin so the below-axes quadrant legend is not clipped
    # (tight_layout does not account for legends anchored outside the axes).
    fig.tight_layout(rect=[0, 0.085, 1, 1])
    savefig(fig, 'Figure3_QuadrantScatter')

# ================================================================
# Figure 4: Project-Level RTAS Distribution (校/省/国)
#   v1.0-cand.5: old Figure4a (mean ± 95% CI point plot) DELETED — its information
#   is fully carried by Figure 4's mean diamonds + the caption stats, and the
#   reviewer verdict was to slim the main text. Only the box+jitter figure remains,
#   renamed Figure4_Distribution (was Figure4b_Distribution).
# ================================================================

def _fig4_load():
    """Shared loader for Fig 4a/4b: tier summary + raw per-project RTAS + Tukey CSV."""
    d = pd.read_csv(DATA / 'heterogeneity' / 'project_level_summary.csv')
    level_en = {'校级': 'University', '省级': 'Provincial', '国家级': 'National'}
    d['_level_en'] = d['_level_label'].map(level_en).fillna(d['_level_label'])
    d = d.sort_values('mean')
    raw = pd.read_csv(ROOT / '01_DATA' / 'final_analysis' / 'table5_project_dataset_n3714_full.csv')
    raw['level_en'] = raw['_level_label'] if '_level_label' in raw.columns else raw['项目等级']
    raw['level_en'] = raw['level_en'].map(level_en).fillna(raw['level_en'])
    order = d['_level_en'].tolist()  # University < Provincial < National by mean
    d['sem'] = d['sd'] / np.sqrt(d['n'])
    d['ci95'] = 1.96 * d['sem']
    data_box = [raw.loc[raw['level_en'] == lv, 'rtas'].dropna().values for lv in order]
    return d, raw, order, data_box

def _fig4_pairwise(data_box):
    """Compute Welch + Cohen d per pair and read strict Tukey HSD from frozen CSV."""
    tukey = pd.read_csv(DATA / 'heterogeneity' / 'tukey_project_level_pairwise.csv')
    cn_to_idx = dict(zip(['校级', '省级', '国家级'], range(3)))
    tukey_dict = {}
    for _, r in tukey.iterrows():
        ia, ib = sorted([cn_to_idx[r['group1']], cn_to_idx[r['group2']]])
        tukey_dict[(ia, ib)] = {'p_adj': float(r['p-adj']), 'meandiff': float(r['meandiff']),
                                'reject': bool(r['reject']),
                                'lower': float(r['lower']), 'upper': float(r['upper'])}
    out = []
    for (ia, ib) in [(0, 1), (1, 2), (0, 2)]:
        va, vb = data_box[ia], data_box[ib]
        _, pw = _stats.ttest_ind(va, vb, equal_var=False, alternative='two-sided')
        d_ = (np.mean(vb) - np.mean(va)) / np.sqrt((np.var(va, ddof=1) + np.var(vb, ddof=1)) / 2)
        out.append((ia, ib, pw, d_, tukey_dict[(ia, ib)]))
    return out

def fig4_project_level():
    """MAIN-TEXT Figure 4 (v1.0-cand.5: renamed from Figure4b; Figure4a deleted).
    Chart-only: element definitions (box = IQR, diamond = mean, whiskers = 1.5*IQR,
    jitter = individual projects, brackets = Tukey HSD verdicts) live in the
    manuscript figure caption, per reviewer verdict to shorten the teaching title."""
    inp = 'heterogeneity/project_level_summary.csv + tukey_project_level_pairwise.csv + table5_project_dataset_n3714_full.csv'
    provenance(4, 'Figure 4 Project-Level RTAS Distribution (box+jitter, chart-only; ex-Fig4b, 4a deleted)', inp)
    d, raw, order, data_box = _fig4_load()
    colors = [COLORS['blue'], COLORS['orange'], COLORS['red']]
    x = np.arange(len(order))

    fig = plt.figure(figsize=(10.5, 7.0))
    ax = fig.add_axes([0.09, 0.11, 0.89, 0.76])

    bp = ax.boxplot(data_box, positions=x, widths=0.38, patch_artist=True, showmeans=True,
                    meanprops=dict(marker='D', markerfacecolor='white', markeredgecolor='#222', markersize=8),
                    medianprops=dict(color='#111', linewidth=1.8),
                    whiskerprops=dict(linewidth=1.2),
                    capprops=dict(linewidth=1.2),
                    flierprops=dict(marker='o', markersize=3, markeredgecolor='none',
                                    markerfacecolor='#aaa', alpha=0.5))
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color); patch.set_alpha(0.25); patch.set_edgecolor(color); patch.set_linewidth(1.4)
    rng = np.random.default_rng(42)
    for xi, vals, color in zip(x, data_box, colors):
        jitter = rng.normal(0, 0.045, len(vals))
        ax.scatter(xi + jitter, vals, s=5, c=color, alpha=0.22, edgecolors='none', zorder=2)
    ax.axhline(0, color='#999', linewidth=0.7, linestyle=':')

    # Brackets: ONLY the strict Tukey verdict stars (full numbers in bottom panel)
    pairs = _fig4_pairwise(data_box)
    allmax = max(float(np.max(v)) for v in data_box)
    allmin = min(float(np.min(v)) for v in data_box)
    yrange = allmax - allmin
    bracket_h = yrange * 0.06
    y0 = allmax + yrange * 0.16
    spec = [((0, 1), 0.0, COLORS['navy']), ((1, 2), 1.7, '#aa5500'), ((0, 2), 3.6, COLORS['red'])]
    for (ia, ib), hrel, col in spec:
        tk = [p for p in pairs if p[0] == ia and p[1] == ib][0][-1]
        verdict = '***' if tk['reject'] else 'ns'
        yb = y0 + hrel * bracket_h
        riser = bracket_h * 0.22
        ax.plot([x[ia], x[ia]], [yb - riser, yb], color=col, lw=1.4, clip_on=False)
        ax.plot([x[ib], x[ib]], [yb - riser, yb], color=col, lw=1.4, clip_on=False)
        ax.plot([x[ia], x[ib]], [yb, yb], color=col, lw=1.4, clip_on=False)
        ax.text((x[ia] + x[ib]) / 2, yb + bracket_h * 0.05, verdict,
                ha='center', va='bottom', fontsize=11, fontweight='bold', color=col)
    ax.set_ylim(allmin - yrange * 0.06, y0 + 5.3 * bracket_h)
    ax.set_xticks(x); ax.set_xticklabels(order, fontsize=11.5)
    ax.set_ylabel('RTAS (per project, 3,714 observations)', fontweight='bold', fontsize=10.5)
    ax.set_xlabel('Project Level', fontweight='bold', fontsize=10.5)
    fig.suptitle('Per-Project RTAS by Project Funding Level (n = 3,714)',
                 fontweight='bold', fontsize=11.5, y=0.975)

    savefig(fig, 'Figure4_Distribution')

# ================================================================
# (v1.0-cand.5) FigureS2_Top20Colleges DELETED per reviewer verdict: the
# raw-mean Top-20 ranking amplified small-n colleges (n=8/9) and added no
# information beyond Figure 5 (model-adjusted caterpillar) + Figure S1
# (full 40-college raw-mean ranking with uncertainty context in the text).
# ================================================================

def fig5_college_caterpillar():
    """MAIN-TEXT Figure 5 (v1.0-cand.4): college random-effects caterpillar plot.
    Single source = hlm_v2b_college_random_effects.csv (BLUPs + conditional SEs
    extracted from the frozen v2b MixedLM refit; identity-guarded)."""
    inp = 'hlm/hlm_v2b_college_random_effects.csv (BLUPs + conditional SEs from frozen v2b MixedLM)'
    provenance(5, 'College Random Effects Caterpillar (main-text replacement for Top-20 ranking)', inp)
    re_df = pd.read_csv(DATA / 'hlm' / 'hlm_v2b_college_random_effects.csv')
    re_df = re_df.sort_values('blup', ascending=True)  # ascending so rank 1 lands on top row
    re_df['college_en'] = re_df['college'].apply(translate_college)
    n_all = len(re_df)
    n_sig = int(((re_df['blup_ci_low'] > 0) | (re_df['blup_ci_high'] < 0)).sum())
    fig, ax = plt.subplots(figsize=(9.5, max(8.5, 0.30 * n_all + 1.5)))
    for i, (_, r) in enumerate(re_df.iterrows()):
        lo, hi = r['blup_ci_low'], r['blup_ci_high']
        ax.plot([lo, hi], [i, i], color='#888888', linewidth=1.6, zorder=2)
        ax.plot([lo, lo], [i - 0.10, i + 0.10], color='#888888', linewidth=1.3, zorder=2)
        ax.plot([hi, hi], [i - 0.10, i + 0.10], color='#888888', linewidth=1.3, zorder=2)
        ax.scatter([r['blup']], [i], s=46, color=COLORS['navy'], zorder=3)
    ax.axvline(x=0, color='#333', linestyle='--', linewidth=1.1, alpha=0.7)
    labels = [f"{int(r['rank_blup'])}.  {r['college_en']}  (n={int(r['n_projects'])})"
              for _, r in re_df.iterrows()]
    ax.set_yticks(range(n_all))
    ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel('College random intercept (BLUP) with 95% CI — contribution to college-mean RTAS\n'
                  'MixedLM v2b: ICC = 0.738; 39 colleges; CI = BLUP ± 1.96·conditional SE (wider = fewer projects)',
                  fontweight='bold', fontsize=8.8)
    ax.set_title('College Random Effects on Research-Training Alignment (Caterpillar Plot)\n'
                 f'model-adjusted college deviations; {n_sig} of {n_all} colleges have CIs excluding 0',
                 fontweight='bold', fontsize=10.5)
    ax.grid(axis='x', alpha=0.25, linewidth=0.5)
    ax.margins(y=0.012)
    fig.tight_layout()
    savefig(fig, 'Figure5_CollegeCaterpillar')

# ================================================================
# Figure 6: HLM Forest Plot (SINGLE SOURCE = hlm_coefficients.csv = Table 6)
# ================================================================
def fig6_hlm_forest():
    inp = 'hlm/hlm_mixedlm_v2b_primary_coefficients.csv'
    provenance(6, 'HLM v2.0b Random-Intercept MixedLM Forest Plot', inp)
    d = pd.read_csv(DATA / 'hlm' / 'hlm_mixedlm_v2b_primary_coefficients.csv')
    # Exclude intercept and Group Var (variance component, not a predictor)
    d_plot = d[~d['term'].isin(['Intercept', 'Group Var', 'const'])].copy()
    # Friendly labels
    label_map = {
        'is_provincial': 'Provincial (vs. University)',
        'is_national': 'National (vs. University)',
        'year_centered': 'Year (per year, centered at 2022)',
        'log_prior3y': 'Advisor pre-project 3y works  log(1+x)',
        'log_prior_supervision': 'Advisor prior supervised projects  log(1+x)',
        'log_supervision': 'Advisor prior supervised projects  log(1+x)',
        'advisor_count': 'Advisor count',
        'advisor_recent_3y_works_mean': 'Advisor recent-3y works (mean)',
        'advisor_cited_by_count_all_mean': 'Advisor cited-by count (mean)',
    }
    d_plot['label'] = d_plot['term'].map(label_map).fillna(d_plot['term'])
    d_plot = d_plot.sort_values('coef', ascending=True).reset_index(drop=True)

    # Parse ICC / nobs / ngroups from v2b summary (single source)
    icc_val, nobs_val, ngrp_val = 'NA', 'NA', 'NA'
    summ = (DATA / 'hlm' / 'hlm_mixedlm_v2b_primary_summary.txt').read_text(encoding='utf-8')
    m = re.search(r'ICC=([\d.]+)', summ)
    if m: icc_val = m.group(1)
    m = re.search(r'n=([\d,]+),\s*colleges=(\d+)', summ)
    if m:
        nobs_val, ngrp_val = m.group(1), m.group(2)

    fig = plt.figure(figsize=(9.8, 6.2))
    ax = fig.add_axes([0.30, 0.12, 0.66, 0.74])  # wide left margin for labels; chart-only
    y_pos = np.arange(len(d_plot))
    x_range_min = min(d_plot['ci_low'].min(), 0)
    x_range_max = max(d_plot['ci_high'].max(), 0.001)
    x_span = x_range_max - x_range_min
    ax.set_xlim(x_range_min - 0.18 * x_span, x_range_max + 0.22 * x_span)

    # v1.0-cand.4 reviewer-audit "de-dashboard" pass: no red/green background zones,
    # single-colour CIs (sign is already encoded by position vs the 0 line; significance
    # by the star). Only position + CI + star remain -> econometrics-journal style.
    for i, (_, row) in enumerate(d_plot.iterrows()):
        sig = row['stars']
        ax.errorbar(row['coef'], i,
                    xerr=[[row['coef'] - row['ci_low']],
                          [row['ci_high'] - row['coef']]],
                    fmt='o', color=COLORS['navy'], ecolor='#444444', capsize=5,
                    markersize=9, linewidth=2.0, zorder=3)
        # Small significance star just right of the CI cap
        ax.text(row['ci_high'] + 0.03 * x_span, i, sig, ha='left', va='center',
                fontsize=11, fontweight='bold', color='#111111')
    ax.axvline(x=0, color='#333333', linestyle='--', linewidth=1.0, alpha=0.6)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(d_plot['label'].values, fontsize=10)
    ax.set_xlabel('Coefficient (β) with 95% CI', fontweight='bold', fontsize=9.5)
    fig.suptitle('Two-level mixed model (projects nested in colleges, random intercept)\n'
                 f'ICC = {icc_val}   |   n = {nobs_val} projects   |   {ngrp_val} college groups   |   '
                 'exact β, 95% CI and p-values in Table 6',
                 fontweight='bold', fontsize=11, y=0.99)

    savefig(fig, 'Figure6_HLM_Forest')

# ================================================================
# Figure 7: Transition Matrix Heatmap (Matthew Effect stability)
# ================================================================
def fig7_transition_matrix():
    inp = 'matthew_effect/transition_probabilities_year_tercile.csv'
    provenance(7, 'Supervisor Transition Matrix', inp)
    d = pd.read_csv(DATA / 'matthew_effect' / 'transition_probabilities_year_tercile.csv',
                    index_col=0)
    fig, ax = plt.subplots(figsize=(5.5, 5))
    data = d.values * 100
    im = ax.imshow(data, cmap='YlOrRd', aspect='auto', vmin=0, vmax=70)
    for i in range(3):
        for j in range(3):
            ax.text(j, i, f'{data[i,j]:.1f}%', ha='center', va='center',
                    fontsize=11, fontweight='bold',
                    color='white' if data[i,j] > 40 else 'black')
    ax.set_xticks([0, 1, 2])
    ax.set_yticks([0, 1, 2])
    ax.set_xticklabels(['Tercile 1\n(Low)', 'Tercile 2\n(Mid)', 'Tercile 3\n(High)'], fontsize=8)
    ax.set_yticklabels(['Tercile 1\n(Low)', 'Tercile 2\n(Mid)', 'Tercile 3\n(High)'], fontsize=8)
    ax.set_xlabel('To (next year)', fontweight='bold')
    ax.set_ylabel('From (current year)', fontweight='bold')
    ax.set_title('Supervisor Activity Tercile Transition Matrix\n'
                 '(n=736 consecutive pairs, diagonal = position stability)',
                 fontweight='bold', fontsize=9)
    cbar = fig.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label('Transition probability (%)', fontsize=8)
    fig.tight_layout()
    savefig(fig, 'Figure7_TransitionMatrix', subdir='supp')

# ================================================================
# Figure 8: Diffusion-Lag Patterns — TWO-PANEL MERGED (v1.0-cand.4 figure audit:
#   old Fig8 histogram + old Fig9 quadrant boxes combined; LRHT/LRLT undefined
#   quadrants stated in a compact annotation instead of hatched N/A columns)
# ================================================================
def fig8_diffusion_lag_patterns():
    # v1.0-cand.6 SPLIT (user visual review): two standalone files so the manuscript
    # can place them side-by-side in one row at reduced width:
    #   Figure8a_LagDistribution  — (a) overall discrete lag histogram;
    #       legend moved OUTSIDE the axes to the right (was floating over the plot).
    #   Figure8b_LagByQuadrant    — (b) HRLT/HRHT boxplots; the red-border HRHT
    #       value box ("n=5 / 4 at lag 0 / 1 at lag -2") DELETED — fully redundant
    #       with the scatter points and tick labels (exact counts -> caption);
    #       canvas made taller per user request.
    inp = 'diffusion_lag/diffusion_lag_histogram_bins.csv + diffusion_lag/topic_first_year_adoption.csv'
    provenance(8, 'Diffusion-Lag Patterns (split files: overall distribution + defined-lag quadrants)', inp)
    d = pd.read_csv(DATA / 'diffusion_lag' / 'diffusion_lag_histogram_bins.csv')
    agg = pd.read_csv(DATA / 'diffusion_lag' / 'diffusion_lag_aggregate_stats.csv')
    agg_row = agg[agg['group'] == 'OVERALL'].iloc[0]
    n_lag = int(agg_row['n_topics_with_defined_lag'])
    lag_med = float(agg_row['lag_median']); lag_mean = float(agg_row['lag_mean'])
    lag_note = ('Positive lag = research precedes training;  '
                'negative lag = training precedes research.')

    # ---- 8a: discrete integer bar chart, compact xlim (reviewer audit fix) ----
    fig, axA = plt.subplots(figsize=(7.9, 5.6))
    d = d[d['n_topics'] > 0].copy()          # drop empty integer bins
    colors = [COLORS['red'] if c > 0 else COLORS['green'] if c < 0 else COLORS['gray']
              for c in d['lag_year_bin_center']]
    bars = axA.bar(d['lag_year_bin_center'], d['n_topics'], color=colors, alpha=0.75,
                   edgecolor='white', linewidth=0.5, width=0.72)
    axA.axvline(x=0, color='#333', linestyle='--', linewidth=1, alpha=0.5)
    axA.set_xlim(-4.6, 4.6)
    axA.set_xticks(range(-4, 5))
    axA.set_xlabel('Lag (years): project adoption − paper emergence\n'
                   'positive = research leads training', fontweight='bold', fontsize=9.5)
    axA.set_ylabel('Number of topics', fontweight='bold', fontsize=10)
    axA.set_title(f'(a) Overall lag distribution ({n_lag}/886 topics defined; median={lag_med:.1f}, mean={lag_mean:+.2f} yr)',
                  fontweight='bold', fontsize=10.5)
    for bar, n, pct in zip(bars, d['n_topics'], d['pct_topics']):
        axA.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.25,
                 f'{n}\n({pct:.0f}%)', ha='center', fontsize=8, fontweight='bold', color='#333')
    axA.set_ylim(0, d['n_topics'].max() * 1.24)
    legend_elements = [
        mpatches.Patch(facecolor=COLORS['red'], alpha=0.75, label='Positive lag (research → training)'),
        mpatches.Patch(facecolor=COLORS['gray'], alpha=0.75, label='Zero lag (synchronized)'),
        mpatches.Patch(facecolor=COLORS['green'], alpha=0.75, label='Negative lag (training → research)'),
    ]
    axA.legend(handles=legend_elements, loc='upper left', bbox_to_anchor=(1.01, 1.0),
               fontsize=8, frameon=False)
    axA.grid(axis='y', alpha=0.25, linewidth=0.5)
    fig.suptitle('Diffusion-Lag Patterns: Research → Training Adoption Delay\n' + lag_note,
                 fontweight='bold', fontsize=11, y=1.00)
    fig.tight_layout(rect=[0, 0, 1, 0.93])
    savefig(fig, 'Figure8a_LagDistribution')

    # ---- 8b: defined-lag quadrants (HRLT / HRHT only) ----
    # FROZEN DEFINITION: lag uses the SINGLE-YEAR non-trivial-presence rule —
    # paper side: n_paper(y) >= 3 AND pct_paper(y) >= 0.2%; project side:
    # n_project(y) >= 2 AND pct_project(y) >= 0.2%. Empirically 0/10 LRHT and
    # 0/698 LRLT topics ever satisfy the paper-side yearly bar in 2020-2024, so
    # only HRLT (24) and HRHT (5) are drawn; the undefined quadrants are stated
    # in a compact annotation instead of two large hatched panels (v1.0-cand.4
    # reviewer audit: hatched N/A columns were visually dominating the figure).
    dd = pd.read_csv(DATA / 'diffusion_lag' / 'topic_first_year_adoption.csv')
    dd = dd[dd['lag_defined']].copy()
    quadrants_order = ['HRLT_HighResearch_LowTraining', 'HRHT_HighResearch_HighTraining']
    box_vals = [dd[dd['quadrant'] == q]['lag_years'].dropna().values for q in quadrants_order]
    box_colors = [QUADRANT_COLORS[q] for q in quadrants_order]

    fig, axB = plt.subplots(figsize=(6.9, 5.9))   # taller canvas (v1.0-cand.6 user review)
    bp = axB.boxplot(box_vals, positions=[0, 1], widths=0.34, patch_artist=True, showmeans=True,
                     meanprops=dict(marker='D', markerfacecolor='white', markeredgecolor='#111', markersize=8),
                     medianprops=dict(color='#111', linewidth=1.8),
                     whiskerprops=dict(linewidth=1.2),
                     capprops=dict(linewidth=1.2),
                     flierprops=dict(marker='o', markersize=4, markeredgecolor='none',
                                     markerfacecolor='#888', alpha=0.6))
    for patch, color in zip(bp['boxes'], box_colors):
        patch.set_facecolor(color); patch.set_alpha(0.25); patch.set_edgecolor(color); patch.set_linewidth(1.4)

    qsum = pd.read_csv(DATA / 'topic_model' / 'quadrant_overall_summary.csv')
    quadrant_total = dict(zip(qsum['quadrant'], qsum['n_topics']))
    xtick_labs = [f"{QUADRANT_SHORT[q]}\nn_defined = {len(v)}\n({quadrant_total[q]} in quadrant)"
                  for q, v in zip(quadrants_order, box_vals)]
    rng = np.random.default_rng(7)
    for xi, (vals, color) in enumerate(zip(box_vals, box_colors)):
        jx = rng.normal(xi, 0.05, len(vals))
        axB.scatter(jx, vals, c=color, alpha=0.9, s=46, zorder=3,
                    edgecolors='white', linewidth=0.7)
        # v1.0-cand.6: the red-border HRHT value box ("n = 5 topics / 4 at lag 0 /
        # 1 at lag -2") was deleted per user visual review — the scatter points and
        # the n_defined tick label already carry this information; exact counts
        # belong in the manuscript caption, not boxed inside the image.
    axB.axhline(y=0, color='#333', linestyle='--', linewidth=1.1, alpha=0.6, zorder=1)
    axB.axhspan(-5.5, -0.02, color=COLORS['green'], alpha=0.07, zorder=0)
    axB.axhspan(0.02, 5.5, color=COLORS['red'], alpha=0.07, zorder=0)
    axB.set_xticks([0, 1])
    axB.set_xticklabels(xtick_labs, fontsize=9.0)
    axB.set_ylabel('Lag (years), same definition as panel (a)', fontweight='bold', fontsize=9.5)
    axB.set_ylim(-5.1, 5.1)
    axB.set_title('(b) Defined lag by quadrant', fontweight='bold', fontsize=10.5)
    # Top-LEFT gray note kept (v1.0-cand.4): states why LRHT/LRLT have no boxes.
    axB.text(0.02, 0.965,
             'Lag was undefined for ALL LRHT (0/10) and LRLT (0/698) topics\n'
             'under the frozen single-year non-trivial-presence rule.',
             transform=axB.transAxes, ha='left', va='top', fontsize=7.8, color='#555',
             style='italic', linespacing=1.4)

    fig.suptitle('Diffusion-Lag Patterns: Defined Lag by Quadrant\n' + lag_note,
                 fontweight='bold', fontsize=11, y=1.00)
    fig.tight_layout(rect=[0, 0, 1, 0.93])
    savefig(fig, 'Figure8b_LagByQuadrant')

# ================================================================
# Figure 10: Matthew Effect — Lorenz Curve + Pareto Bar
# ================================================================
def fig10_matthew_effect():
    inp = 'matthew_effect/supervisor_gini_pareto.csv + lagged_logit_national_path_dependence*.csv'
    provenance(10, 'Matthew Effect three-panel: Lorenz + Pareto + lagged path-dependence OR', inp)
    # Read audit JSON for Lorenz curve computation
    audit = json.loads((DATA / 'matthew_effect' / 'matthew_effect_audit.json').read_text(encoding='utf-8'))
    # Reconstruct Lorenz curve from raw project data for national-project allocation
    proj = pd.read_csv(ROOT / '01_DATA' / 'final_analysis' / 'table5_project_dataset_n3714_full.csv')
    proj['is_national'] = proj['项目等级'].astype(str).str.contains('国家级').astype(int)
    by_sup = proj.groupby('advisor').agg(n_national=('is_national', 'sum')).sort_values('n_national', ascending=False)
    vals = by_sup['n_national'].values.astype(float)
    vals_sorted = np.sort(vals)
    n = len(vals_sorted)
    cum = np.cumsum(vals_sorted)
    total = cum[-1] if cum[-1] > 0 else 1
    lorenz_y = np.concatenate([[0], cum / total])
    lorenz_x = np.arange(n + 1) / n

    # Panel (c): lagged t-1 -> t path-dependence logistic (v1.0-cand.2, replaces the
    # withdrawn circular cross-sectional OR=6.085)
    lgA = pd.read_csv(DATA / 'matthew_effect' / 'lagged_logit_national_path_dependence.csv')
    lgB = pd.read_csv(DATA / 'matthew_effect' / 'lagged_logit_national_path_dependence_sampleB.csv')
    natA = lgA[lgA['term'] == 'nat_lag'].iloc[0]
    natB = lgB[lgB['term'] == 'nat_lag'].iloc[0]

    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(14.2, 5.0),
                                        gridspec_kw=dict(width_ratios=[1.0, 0.85, 1.0], wspace=0.44))
    # (a) Lorenz curve
    ax1.plot(lorenz_x, lorenz_y, color=COLORS['red'], linewidth=2, label=f'National grants (Gini={audit["gini"]["value_national_projects"]:.3f})')
    ax1.plot([0, 1], [0, 1], '--', color=COLORS['gray'], linewidth=1, label='Perfect equality')
    ax1.fill_between(lorenz_x, lorenz_x, lorenz_y, alpha=0.1, color=COLORS['red'])
    ax1.set_xlabel('Cumulative share of supervisors (sorted)', fontweight='bold')
    ax1.set_ylabel('Cumulative share of national projects', fontweight='bold')
    ax1.set_title('(a) Lorenz Curve: National Project Allocation\n(Gini = 0.767, Top 5% hold 34.0%)', fontweight='bold', fontsize=9)
    ax1.legend(fontsize=7.5)

    # (b) Pareto bar
    pareto_data = audit['gini']['pareto_national_shares_pct']
    # v1.0-cand.6: top50 bar removed (user visual review) - a constant 100% gray
    # slab carried no information, dwarfed the informative bars, and squeezed
    # panel (c)'s y-tick labels in the inter-panel gutter.
    pcts = ['top1', 'top5', 'top10', 'top20']
    vals_p = [pareto_data.get(f'{p}_national_share_pct', 0) for p in pcts]
    bars = ax2.bar(pcts, vals_p, color=[COLORS['red'], COLORS['orange'], COLORS['orange'],
                                         COLORS['blue']], alpha=0.8, width=0.6)
    ax2.axhline(y=5, color='#999', linestyle='--', linewidth=0.8, label='Equal share line')
    for bar, v in zip(bars, vals_p):
        ax2.text(bar.get_x() + bar.get_width()/2, v + 1, f'{v:.1f}%', ha='center', fontsize=8, fontweight='bold')
    ax2.set_xlabel('Top N% supervisors', fontweight='bold')
    ax2.set_ylabel('Share of national projects (%)', fontweight='bold')
    ax2.set_title('(b) Pareto Concentration\n(Top 20% supervisors hold 76.8%)', fontweight='bold', fontsize=9)
    ax2.legend(fontsize=7.5)

    # (c) Lagged path-dependence OR forest (two samples).
    # y-tick labels kept SHORT so they stay inside the inter-panel margin
    # (long labels intruded into panel (b)); n / p moved into the in-plot
    # annotation under each OR (v1.0-cand.4 visual fix).
    rows = [(f"Sample A: active t-1 & t\n(n=736 cells / 491 advisors)",
             float(natA['OR']), float(natA['OR_ci95_lo']), float(natA['OR_ci95_hi']), natA['mark'],
             f"p = {natA['p_value']:.1e}"),
            (f"Sample B: expanded risk set\n(n=2,302 / 1,621 advisors)",
             float(natB['OR']), float(natB['OR_ci95_lo']), float(natB['OR_ci95_hi']), natB['mark'],
             f"p = {natB['p_value']:.1e}")]
    for yi, (lab, OR, lo, hi, mark, ptxt) in enumerate(rows):
        ax3.plot([lo, hi], [yi, yi], color='#444444', linewidth=2.2, zorder=2)
        ax3.plot([lo, lo], [yi - 0.06, yi + 0.06], color='#444444', linewidth=1.6, zorder=2)
        ax3.plot([hi, hi], [yi - 0.06, yi + 0.06], color='#444444', linewidth=1.6, zorder=2)
        ax3.scatter([OR], [yi], s=90, color=COLORS['navy'], zorder=3)
        ax3.text(hi + 0.10, yi + 0.10, f'OR = {OR:.2f} [{lo:.2f}, {hi:.2f}] {mark}',
                 va='center', fontsize=8.5, fontweight='bold', color='#111')
        ax3.text(hi + 0.10, yi - 0.22, f'{ptxt}', va='center', fontsize=7.2, color='#555')
    ax3.axvline(x=1, color='#333', linestyle='--', linewidth=1.1, alpha=0.7)
    ax3.text(1, -0.44, 'OR = 1\n(no persistence)', ha='center', va='bottom',
             fontsize=7.5, color='#555', linespacing=1.3)
    ax3.set_yticks([0, 1])
    ax3.set_yticklabels(['Sample A\nactive t-1 & t', 'Sample B\nexpanded risk set'],
                        fontsize=8.5)
    ax3.set_xlim(0.9, 4.3)
    ax3.set_ylim(-0.75, 1.85)
    ax3.set_xlabel("Odds ratio of a national project in year t\ngiven one in t-1 (logit, year FE, SE clustered by advisor)",
                   fontweight='bold', fontsize=8.5)
    ax3.set_title('(c) Path Dependence: Lagged Logistic\n(national project persistence t-1 -> t)', fontweight='bold', fontsize=9)
    ax3.grid(axis='x', alpha=0.25, linewidth=0.5)

    fig.suptitle('The Matthew Effect in National Project Allocation: Concentration AND Persistence',
                 fontweight='bold', fontsize=11.5, y=1.02)
    fig.tight_layout()
    savefig(fig, 'Figure10_MatthewEffect')

# ================================================================
# Figure 11: Quadrant Summary Grouped Bars
# ================================================================
def fig11_quadrant_summary():
    inp = 'topic_model/quadrant_overall_summary.csv'
    provenance(11, 'Quadrant Summary Bars (clustered-only denominators; demoted to Supplementary)', inp)
    d = pd.read_csv(DATA / 'topic_model' / 'quadrant_overall_summary.csv')
    d = d.sort_values('quadrant')
    fig, axes = plt.subplots(1, 3, figsize=(11, 4))
    # Subplot 1: n_topics
    colors = [QUADRANT_COLORS.get(q, COLORS['gray']) for q in d['quadrant']]
    short_labels = [QUADRANT_SHORT.get(q, q) for q in d['quadrant']]
    axes[0].bar(short_labels, d['n_topics'], color=colors, alpha=0.8, width=0.6)
    for i, v in enumerate(d['n_topics']):
        axes[0].text(i, v + 2, str(v), ha='center', fontweight='bold', fontsize=9)
    axes[0].set_ylabel('Number of topics', fontweight='bold')
    axes[0].set_title('Topic count', fontweight='bold')

    # Subplot 2: n_papers
    axes[1].bar(short_labels, d['n_papers_total'], color=colors, alpha=0.8, width=0.6)
    for i, v in enumerate(d['n_papers_total']):
        axes[1].text(i, v + 50, str(v), ha='center', fontweight='bold', fontsize=9)
    axes[1].set_ylabel('Number of papers', fontweight='bold')
    axes[1].set_title('Clustered paper documents', fontweight='bold')

    # Subplot 3: n_projects
    axes[2].bar(short_labels, d['n_projects_total'], color=colors, alpha=0.8, width=0.6)
    for i, v in enumerate(d['n_projects_total']):
        axes[2].text(i, v + 15, str(v), ha='center', fontweight='bold', fontsize=9)
    axes[2].set_ylabel('Number of projects', fontweight='bold')
    axes[2].set_title('Clustered project documents', fontweight='bold')

    fig.suptitle('Four-Quadrant Topic Summary (v1.0-cand.4: demoted to Supplementary)\n'
                 'Denominators = clustered documents only; BERTopic outliers (38.47% of docs) are outside the four quadrants',
                 fontweight='bold', fontsize=10.5, y=1.04)
    fig.tight_layout()
    savefig(fig, 'Figure11_QuadrantSummary', subdir='supp')

# ================================================================
# Figure 12: College RTAS Ranking (Top 20 + Bottom 5, fontsize=10)
# ================================================================
def fig12_college_rtas_ranking():
    inp = 'heterogeneity/college_rtas_summary_all.csv'
    provenance(12, 'College RTAS Full Ranking (All 40, Appendix)', inp)
    d = pd.read_csv(DATA / 'heterogeneity' / 'college_rtas_summary_all.csv')
    d = d.sort_values('rtas_mean')  # ascending for horizontal bar (rank 40 top → rank 1 bottom)
    d['college_en'] = d['college'].apply(translate_college)
    n_all = len(d)
    fig, ax = plt.subplots(figsize=(9, max(10, 0.32 * n_all + 2)))
    # Color mapped to VALUE (same normalization language as Figure 5)
    norm = plt.Normalize(vmin=d['rtas_mean'].min(), vmax=d['rtas_mean'].max())
    cmap = plt.cm.RdYlGn  # red = low RTAS, green = high RTAS
    colors = cmap(norm(d['rtas_mean'].values))
    bars = ax.barh(range(n_all), d['rtas_mean'], color=colors,
                   edgecolor='white', linewidth=0.3, height=0.7)
    ax.set_yticks(range(n_all))
    # Ascending = lowest RTAS on top (most-worst → #40 at top), highest RTAS at bottom (#1 at bottom).
    # Use "N.  Name" format (no hash) per user request. rank column already holds 1..40 (1=best).
    rank_labels = [f"{int(r)}.  {name}" for r, name in zip(d['rank'], d['college_en'])]
    ax.set_yticklabels(rank_labels, fontsize=8)
    ax.set_xlabel('RTAS (mean)', fontweight='bold')
    ax.set_title(f'All {n_all} Colleges by RTAS — Full Ranking (Appendix)\n'
                 'College ANOVA: F(38,3674)=195.45, p < .001, η²=66.90%',
                 fontweight='bold', fontsize=10)
    for i, (val, n) in enumerate(zip(d['rtas_mean'], d['n_projects'])):
        ax.text(val + 0.003, i, f'{val:.3f} (n={n})', va='center', fontsize=6.5)
    ax.set_xlim(0, max(d['rtas_mean']) * 1.25)
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    cbar = fig.colorbar(sm, ax=ax, shrink=0.5, pad=0.12)
    cbar.set_label('RTAS color scale:  red = lower alignment  →  green = higher alignment', fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    fig.tight_layout()
    savefig(fig, 'FigureS1_CollegeRTAS_Full40', subdir='supp')

# ================================================================
# Figure 13: Temporal Topic Dynamics — TWO-PANEL (v1.0-cand.4; demoted to
#   SUPPLEMENTARY in v1.0-cand.5 per reviewer verdict: second-layer finding)
#   Panel A: Top-15 share vs clustered long-tail share (two lines, the
#            diversification trend at one glance)
#   Panel B: Top-15 topics × 2020-2024 heatmap of project-side prevalence
#   (replaces the 15-colour stacked area. DENOMINATOR (v1.0-cand.5 correction,
#    reviewer-audited): shares are percentages of ALL project documents per
#    year — the frozen CSV's denom_project column sums to exactly 3,714 across
#    2020-2024 (853+924+435+664+838), and Top-15 (17.6%) + Other clustered
#    (29.5%) ≈ 47% = clustered share of all projects. The old "clustered docs"
#    axis label was factually wrong. Topics shown = BERTopic clusters only;
#    the "Other" band is explicitly "Other clustered topics".)
# ================================================================
def fig13_topic_dynamics():
    inp = 'topic_model/topic_yearly_prevalence_for_diffusion_lag.csv + topic_model/topic_info.csv (topic words)'
    provenance(13, 'Temporal Topic Dynamics — Top-15 vs clustered long tail (trend) + prevalence heatmap', inp)
    d = pd.read_csv(DATA / 'topic_model' / 'topic_yearly_prevalence_for_diffusion_lag.csv')
    ti = pd.read_csv(DATA / 'topic_model' / 'topic_info.csv')
    pivot = d.pivot_table(index='year', columns='topic_id', values='pct_project', fill_value=0)
    top_topics = pivot.sum().nlargest(15).index          # by lifetime total share
    pivot_top = pivot[top_topics]
    top15_share = pivot_top.sum(axis=1)
    longtail_share = pivot.drop(columns=top_topics).sum(axis=1)
    years = pivot_top.index.values

    # --- shared topic gloss (c-TF-IDF based short English labels) ---
    TOPIC_GLOSS = {
        5:   'Language learning (Chinese/English)',
        72:  'Robots / robotics',
        125: 'Drones / unmanned vehicles',
        22:  'Dental implants',
        216: 'Online learning / big data',
        6:   'Urban land / ecology',
        160: 'College English / talent education',
        429: 'Internet platforms & legal governance',
        333: 'Event cameras / imagers',
        3:   'Blockchain / privacy computing',
        196: 'Deep learning',
        140: 'Food safety',
        2:   'Lithium-ion batteries',
        345: 'Elderly care / aging',
        81:  'Video quality / coding',
    }
    def auto_gloss(tid):
        row = ti.loc[ti['Topic'] == tid, 'Name']
        if len(row) == 0:
            return f'Topic {tid}'
        toks = [t for t in str(row.iloc[0]).split('_')[1:] if t.isascii() and t.isalpha()]
        seen = []
        for t in toks:
            if t not in seen:
                seen.append(t)
        return ' '.join(seen[:3]) if seen else f'Topic {tid}'

    fig, (axA, axB) = plt.subplots(1, 2, figsize=(13.5, 6.2),
                                   gridspec_kw=dict(width_ratios=[1.0, 1.15], wspace=0.24))
    # ---- Panel A: two-line diversification trend ----
    axA.plot(years, top15_share.values, 'o-', color=COLORS['blue'], linewidth=2.2, markersize=7,
             label='Top-15 mainstream topics', zorder=4)
    axA.plot(years, longtail_share.values, 's-', color=COLORS['orange'], linewidth=2.2, markersize=7,
             label='Other clustered topics (long tail, 871 topics)', zorder=4)
    for x_, y_ in zip(years, top15_share.values):
        axA.annotate(f'{y_:.1f}', (x_, y_), textcoords='offset points', xytext=(0, -16),
                     ha='center', fontsize=9, color=COLORS['blue'], fontweight='bold')
    for x_, y_ in zip(years, longtail_share.values):
        axA.annotate(f'{y_:.1f}', (x_, y_), textcoords='offset points', xytext=(0, 10),
                     ha='center', fontsize=9, color='#b35c00', fontweight='bold')
    axA.set_xticks(years)
    axA.set_xlabel('Year', fontweight='bold', fontsize=11)
    axA.set_ylabel('Share of all project documents (%)', fontweight='bold', fontsize=10)
    axA.set_title('(a) Mainstream topics decline, long tail diversifies', fontweight='bold', fontsize=11)
    axA.legend(fontsize=8.5, loc='center right', framealpha=0.9)
    axA.set_ylim(0, max(longtail_share.max(), top15_share.max()) * 1.22)
    axA.margins(x=0.06)
    axA.grid(axis='y', alpha=0.25, linewidth=0.5)

    # ---- Panel B: 15 × 5 heatmap (rows sorted by lifetime share, top = largest) ----
    order_desc = list(top_topics)  # nlargest already sorted desc
    mat = pivot_top.loc[:, order_desc].T  # rows=topics, cols=years
    row_labels = [f'T{int(tid)}  {TOPIC_GLOSS.get(tid, auto_gloss(tid))}' for tid in order_desc]
    im = axB.imshow(mat.values, aspect='auto', cmap='YlOrRd', vmin=0)
    axB.set_xticks(range(len(years)))
    axB.set_xticklabels(years, fontsize=10)
    axB.set_yticks(range(len(order_desc)))
    axB.set_yticklabels(row_labels, fontsize=7.8)
    vmax = mat.values.max()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            v = mat.values[i, j]
            axB.text(j, i, f'{v:.2f}', ha='center', va='center', fontsize=6.6,
                     color='white' if v > vmax * 0.55 else '#222')
    cbar = fig.colorbar(im, ax=axB, shrink=0.82, pad=0.015)
    cbar.set_label('Project-side prevalence (% of all projects / yr)', fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    axB.set_title('(b) Top-15 topic prevalence heatmap', fontweight='bold', fontsize=11)

    fig.suptitle('Temporal Topic Dynamics in ITTP Projects, 2020-2024  '
                 '(shares of all projects per year; topics = BERTopic clusters)',
                 fontweight='bold', fontsize=12.5, y=0.99)
    savefig(fig, 'Figure13_TopicDynamics', subdir='supp')

# ================================================================
# MAIN
# ================================================================
if __name__ == '__main__':
    print(f'[10_generate_figures] v{CFG["version"]}  DPI={DPI}')
    print(f'  Output main: {OUT_MAIN}')
    print(f'  Output supp: {OUT_SUPP}')
    print(f'  CJK font: {CJK_FONT}')
    print()
    print('Generating all figures from frozen 03_FINAL_ANALYSIS CSVs...')
    print()

    fig2_roadmap()
    fig3_quadrant_scatter()
    fig4_project_level()
    fig5_college_caterpillar()   # MAIN-TEXT Figure 5 (model-adjusted, ICC-consistent)
    fig6_hlm_forest()
    fig7_transition_matrix()     # demoted -> supplementary (supervisor tercile, not the main path-dependence test)
    fig8_diffusion_lag_patterns()  # v1.0-cand.6: split into Figure8a + Figure8b (two standalone files)
    fig10_matthew_effect()
    fig11_quadrant_summary()     # demoted -> supplementary
    fig12_college_rtas_ranking() # -> FigureS1 (supplementary)
    fig13_topic_dynamics()       # redesigned two-panel (replaces 15-band stacked area)

    print()
    print(f'[10_generate_figures] DONE. {len(list(OUT_MAIN.glob("*.pdf")))} PDF + '
          f'{len(list(OUT_MAIN.glob("*.png")))} PNG files in {OUT_MAIN}')
